### ISSUE TITLE
Question: whether the left toolbar may the hidden by double click?

### ISSUE THREAD

**Issue by zhouxs1023** [guillaumechereau/goxel#100]
![3606421106858099](https://user-images.githubusercontent.com/905931/38554521-7aca11d8-3cf5-11e8-954e-1faf52c133e3.png)  ===>![3](https://user-images.githubusercontent.com/905931/38555498-ee53f5e4-3cf8-11e8-93bb-627823e9af7e.png)

**Comment by guillaumechereau** [comment]
Not at the moment, but that would be nice yes.

**Comment by zhouxs1023** [comment]
Is there a plan to increase this function later?

**Comment by guillaumechereau** [comment]
I can probably do that soon.  Not with a double click though, most likely with a button somewhere to toggle the left panel.

**Comment by zhouxs1023** [comment]
Look forward to add this function

**Comment by guillaumechereau** [comment]
I just pushed a fix for that.
