### ISSUE TITLE
[Feature Request] Both types of Marching Cubes available on export to .PLY

### ISSUE THREAD

**Issue by YarlBoro** [guillaumechereau/goxel#102]
I would to request a small enhancement. Currently there are two modes of Marching Cubes in Goxel, normal & flat. But on exporting such mesh to PLY, Goxel always use 'flat' mode.
This 'flat' look is great for organic or irregular stuff (trees, clouds, rocks, etc), but machines/vehicles look way better with 'normal' Marching Cubes.
Would it be possible to add PLY export of MC 'normal' mode too?

On a side note, will Maching Cubes be ever available via Cycles renderer?

**Comment by guillaumechereau** [comment]
Done.

**Comment by YarlBoro** [comment]
Thank You!
