### ISSUE TITLE
Goxel crash after pressing UI element

### ISSUE THREAD

**Issue by YarlBoro** [guillaumechereau/goxel#103]
I can start Goxel & i.e. rotate bounding box with keyboard. But if I try to press any UI button, or File/Edit/View/Help menus, Goxel crash.

Here is crash report:

[goxel-crash-20-04-2018.txt](https://github.com/guillaumechereau/goxel/files/1931899/goxel-crash-20-04-2018.txt)

**Comment by guillaumechereau** [comment]
Can you try again with be last version? It seems to work on my Mac.

**Comment by YarlBoro** [comment]
Sorry, I was away from computer for rest of a day. I will check it in few hours & let You know.

Thanks!

**Comment by guillaumechereau** [comment]
OK great! I'll try to make a new release soon, maybe today if I have time.
