### ISSUE TITLE
Extrude image into plane

### ISSUE THREAD

**Issue by moonheart08** [guillaumechereau/goxel#108]
As of now, image layers are uneditable, and there is no way to 'extrude' said image into an editable layer made of voxels. No I do not mean shape detection, i mean simply turn each pixel into a voxel.
My purpose for this is to give some textures i'm using for a Minecraft mod a nicer look.

**Comment by moonheart08** [comment]
Yup. Thats all i'm asking for. :)

**Comment by guillaumechereau** [comment]
There is now an option to turn a image layer into a mesh of 1px height.  I think that should solve this issue so I close it for now.

**Comment by Houstonruss** [comment]
<img width="510" height="603" alt="Image" src="https://github.com/user-attachments/assets/4bb0ee3e-64c6-460c-99d8-02eaea87cb5a" />
For anyone looking for this, because it was hard for me to find, it's here!!!
Thanks for the software it's pretty nice so far!
