### ISSUE TITLE
Latest version for iOS unstable 

### ISSUE THREAD

**Issue by tpebic** [guillaumechereau/goxel#114]
Been keeping designs with in the 126x126x126 for easy import into magical voxel.

Lately the app has been crashing a lot when working on any design new or old. I get about 50-75 motions and risk the app crashing. When I reopen I loose what I did and have to repeat. 

Running latest iOS and app version.

**Comment by guillaumechereau** [comment]
Hello.  Can you tell me what device you are using?

**Comment by tpebic** [comment]
Yeah for sure, iPad Pro 9.7 inch 2016 model

**Comment by guillaumechereau** [comment]
Ok, I will try to rent one and see if I can reproduce the bug.

**Comment by tpebic** [comment]
Sounds good, I posted a video to my youtube account for you to see what happens. 
https://www.youtube.com/watch?v=eq9L-Zcb_Ng

It is nine minutes long, because I wanted to show what happens after the crash, and how long it takes to crash again after I open it up again.

**Comment by tpebic** [comment]
I think I sent the right one, no way to name them lol..

But either way, no matter what I do in the app, it tends to crash after a certain time, might be a caching issue or something, if I work on new builds or old builds. 

Started happening sometime in the spring after you release the debug and cloud update I think. Happened the odd time previously, but every one in a while, like if I tried to level a huge amount of blocks or delete/paint a large amount. 

You are right, it is completely random, just sort of crashes randomly after a certain amount of time.

**Comment by guillaumechereau** [comment]
Yes it looks like a cache issue.  Is there a way to get a crash report on iOS?  I am a bit busy with other stuff this week but I will try to have a look at that this week end.  Sorry about that!

**Comment by tpebic** [comment]
ill have to try and figure out how to locate a crash report, I know there is an option for app developers to implement a crash reporting. 

Ill see what I can find on my end.

**Comment by guillaumechereau** [comment]
I updated the ios version, with many changes, including reducing the size of the rendering cache.  I think this is what used to cause a problem.  Let me know if you have time to test it out.

**Comment by tpebic** [comment]
What ever you did worked perfectly.. 

I have been using it non stop with little to no crashes. The last crashed happened cause I tried to extrude a huge level of voxels... Other then that its perfect!
