### ISSUE TITLE
voxeltoy: online webgl goxel build

### ISSUE THREAD

**Issue by guillaumechereau** [guillaumechereau/goxel#117]
Not really an issue, but just to let people know that I did a small experimental webgl version of goxel with an associated program editor to create procedural voxels images:

https://voxeltoy.com

Feel free to comment here.

**Comment by YarlBoro** [comment]
So 'ShaderToy of voxel world' is a real thing now. This can be super useful in the future for knowledge exchange :)
Some sort of export option would be handy for users. I.E. save current frame to PNG 1024x1024, or low-framerate animated gif showing few stages of drawing. 
Idea: an option to generate special link to VoxelToy project. Recipient of such link would see just a viewport animating. At the bottom there would be place for short message and button to bring full VoxelToy view. 
It would be like sending someone animated gif, but would be procedural instead. I can imagine geeks like me sending some generative code back and forth among their geeky friends, modding code each time :)

One more little thing. I've tried VoxelToy on my iPhone and there is no way to rotate view. Something like viewport rotation slider in iOS version of Goxel, would be handy.

As usual, just humble random thoughts :) Have a good day
