### ISSUE TITLE
directive writing up to 255 bytes into a region of size 128

### ISSUE THREAD

**Issue by FedericoCeratto** [guillaumechereau/goxel#118]
Build failure using gcc version 8.2.0 :

```
src/formats/gox.c: In function ‘load_from_file’:
src/formats/gox.c:502:44: error: ‘%s’ directive writing up to 255 bytes into a region of size 128 [-Werror=format-overflow=]
                     sprintf(camera->name, "%s", dict_value);
                                            ^~   ~~~~~~~~~~
In file included from /usr/include/stdio.h:862,
                 from src/goxel.h:43,
                 from src/formats/gox.c:20:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 1 and 256 bytes into a destination of size 128
```

**Comment by FedericoCeratto** [comment]
There's a number of warning in GCC that I had to prevent from being treated as errors by removing -Wformat and adding -Wno-class-memaccess -Wno-error=format-overflow

**Comment by guillaumechereau** [comment]
Thanks.  I think I just solved this particular bug.  For the other ones I need to see how to use gcc v8.2.0.  What distribution are you using?  On debian 7.3.0 seems to be the default.

**Comment by guillaumechereau** [comment]
Closing cause all those errors have been fix as far as I know now.

**Comment by FedericoCeratto** [comment]
@guillaumechereau The default in Testing and the upcoming Buster release is 8.3.0 https://packages.debian.org/buster/gcc
