### ISSUE TITLE
Enables sse flags by default -> break aarch64

### ISSUE THREAD

**Issue by Mic92** [guillaumechereau/goxel#125]
Also it seems to hide sse specific code behind feature flags goxel seems to pass `-msse2` by default.
This breaks the build on arm8 at the moment. In case upstream cares of support on this upstream it might be a good idea to not unconditionally include this.
Recognized while reviewing `0.8.0 -> 0.8.1` update: https://github.com/NixOS/nixpkgs/pull/47789#issuecomment-426743443

**Comment by guillaumechereau** [comment]
Should be fixed by now.  Please reopen if the issue is still there.

**Comment by Mic92** [comment]
Is the fix in a released version?

**Comment by guillaumechereau** [comment]
Yes, the release 0.8.3 should work.  I totally removed all the cycles code that required the sse2 flags.
