### ISSUE TITLE
Layer transparency :)

### ISSUE THREAD

**Issue by tpebic** [guillaumechereau/goxel#128]
So I know you have been struggling to implement a transparency effect. 

So would it be possible to set a transparency for layers? 

If I have blue as water on the second layer, would it be possible to have a transparency option to make the entire second layer transparent? 

That might be a slight hack and work around?

**Comment by guillaumechereau** [comment]
I think it should be possible some ways.  I might do a quick hack to make it work in a simple form first.

**Comment by guillaumechereau** [comment]
Transparency layers are now possible using materials.  I close this issue for now.
