### ISSUE TITLE
Mac OS build has no executable flag on Contents/MacOS/goxel

### ISSUE THREAD

**Issue by kolen** [guillaumechereau/goxel#13]
Zip file in Mac OS build v0.2.0 has ``-rw-r--r--`` permissions (no executable flag) on ``Contents/MacOS/goxel`` so app fails to start:

![image](https://cloud.githubusercontent.com/assets/24191/13894991/22e387f0-ed7f-11e5-8559-53c946f362c1.png)

(Workaround to start it: ``chmod +x /Applications/goxel.app/Contents/MacOS/goxel``)

**Comment by guillaumechereau** [comment]
Thanks for letting me know.  I will try to fix that in the next release.

**Comment by guillaumechereau** [comment]
Hey, I just changed the mac release build, can you try it out again and see if ti works better now?

**Comment by kolen** [comment]
It works now.

**Comment by guillaumechereau** [comment]
Good!  Thanks again.
