### ISSUE TITLE
Can't compile on MacOS 

### ISSUE THREAD

**Issue by YarlBoro** [guillaumechereau/goxel#130]
Hi! I've tried to compiled Goxel today. Compilation fails at this point:

> Ld build/Release/goxel.app/Contents/MacOS/goxel normal x86_64
>     cd /Users/michalborowski/Downloads/goxel-master/osx/goxel
>     export MACOSX_DEPLOYMENT_TARGET=10.9
>     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -L/Users/michalborowski/Downloads/goxel-master/osx/goxel/build/Release -F/Users/michalborowski/Downloads/goxel-master/osx/goxel/build/Release -filelist /Users/michalborowski/Downloads/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/Objects-normal/x86_64/goxel.LinkFileList -Xlinker -rpath -Xlinker @executable_path/../Frameworks -mmacosx-version-min=10.9 -Xlinker -object_path_lto -Xlinker /Users/michalborowski/Downloads/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/Objects-normal/x86_64/goxel_lto.o -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx -Xlinker -add_ast_path -Xlinker /Users/michalborowski/Downloads/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/Objects-normal/x86_64/goxel.swiftmodule -lz -framework CoreFoundation -framework OpenGL -Xlinker -dependency_info -Xlinker /Users/michalborowski/Downloads/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/Objects-normal/x86_64/goxel_dependency_info.dat -o /Users/michalborowski/Downloads/goxel-master/osx/goxel/build/Release/goxel.app/Contents/MacOS/goxel
> Undefined symbols for architecture x86_64:
>   "_box_edit", referenced from:
>       _iter in selection.o
>       _iter in move.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> ** BUILD FAILED **

**Comment by YarlBoro** [comment]
After corrections for compilation on Linux,  MacOS works now too. 
Issue can be closed. 

Thank You!

On a sidenote, could You describe new 'shape layer' functionality? Is this sth like parametric objects in 3D modelling programs? I've tried using it & understanding, but it seems to be still WIP.

**Comment by guillaumechereau** [comment]
But eventually I was thinking this could be linked to a program, either in the current procedural language, or in lua, so that you can generate all kind of procedural shapes.

**Comment by YarlBoro** [comment]
Nice addition. Besides speed, it adds precision. Less counting voxels on screen, while trying to make shape with exact dimensions, yay!

Scripting/Lua shapes generation - fingers crossed, I can imagine this one is quite complex.

**Comment by guillaumechereau** [comment]
I started a branch to add lua scripting support.  This will allow to run scripts from command lines.  Here is an example of a lua script that run a procedual prog and save the mesh to a file.

    prog = [=[
        shape main {
            cube [s 32]
        }
    ]=]

    mesh = mesh_new()
    mesh_set_at(mesh, {0, 0, 0}, {255, 255, 255, 255})
    proc_run(prog, mesh)
    mesh_export_as_obj(mesh, "/tmp/test.obj")

**Comment by YarlBoro** [comment]
That was fast! 
Thanks for example, I'll try it today.

**Comment by guillaumechereau** [comment]
I added an first example of script in the sources.
![screenshot from 2018-12-09 16-38-59](https://user-images.githubusercontent.com/107679/49695134-1bec2e80-fbd1-11e8-8df2-f001db786b23.png)

**Comment by YarlBoro** [comment]
I tried to compile latest version from Lua branch, but sth goes wrong:

> #include "goxel.h"
>          ^
> /Users/michal/Documents/goxel-lua/src/goxel.h:32:10: note: in file included from /Users/michal/Documents/goxel-lua/src/goxel.h:32:
> #include "action.h"
>          ^
> /Users/michal/Documents/goxel-lua/osx/goxel/../../src/action.h:7:10: error: 'lua.h' file not found
> #include "lua.h"
>          ^
> 1 error generated.
> <unknown>:0: error: failed to emit precompiled header '/Users/michal/Documents/goxel-lua/osx/goxel/build/SharedPrecompiledHeaders/goxel-Bridging-Header-swift_WQI8VCMVXHWC-clang_R7SZBTYITDIF.pch' for bridging header '/Users/michal/Documents/goxel-lua/osx/goxel/goxel/goxel-Bridging-Header.h'
> /Users/michal/Documents/goxel-lua/osx/goxel/goxel/goxel-Bridging-Header.h:12:10: note: in file included from /Users/michal/Documents/goxel-lua/osx/goxel/goxel/goxel-Bridging-Header.h:12:
> #include "goxel.h"
>          ^
> /Users/michal/Documents/goxel-lua/osx/goxel/../../src/goxel.h:32:10: note: in file included from /Users/michal/Documents/goxel-lua/osx/goxel/../../src/goxel.h:32:
> #include "action.h"
>          ^
> 
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	CompileSwift normal x86_64 /Users/michal/Documents/goxel-lua/osx/goxel/goxel/AppDelegate.swift
> 	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
> (2 failures)

**Comment by guillaumechereau** [comment]
Yes that's the usual problem: as I add files in the project I need to also update it in xcode.  But since I primarily work on linux I don't do that very often.

On a side note, I am thinking if it would be a better idea to use javascript as a scripting language instead of lua.  Any opinion on that?

**Comment by guillaumechereau** [comment]
I just pushed on the lua branch, it should compile now.

**Comment by YarlBoro** [comment]
> Yes that's the usual problem: as I add files in the project I need to also update it in xcode. But since I primarily work on linux I don't do that very often.

Ok. 

> On a side note, I am thinking if it would be a better idea to use javascript as a scripting language instead of lua. Any opinion on that?

I can't really compare it. I only used a little bit of javascript & rather simplistic After Effects expressions. 
Probably it comes down to whats easier for You to maintain, while being flexible. 

I think those feats are worth keeping in mind while deciding the future of scripting in Goxel:
- ability to save a mesh/image as script iterates, so we can i.e. save stages of procedural generation as frames or generate some other kind of images sequence i.e. light rotating around model (day-night cycle, etc.)
- set camera/ move camera to precise position(s) & angles - for sprite-sheets
- export/modify layer via script using layer name rather than layer number in stack
- modify voxel colours, shift palette - for palette replacement or tricks like oldschool Amiga color cycling
- remove/'not-show-on-rendered-image' voxels of certain colour

**Comment by YarlBoro** [comment]
I've tried to compile latest version, but it failed at this point:

> /Users/michalborowski/Downloads/goxel-master 2/osx/goxel/goxel/AppDelegate.swift:206:45: error: type 'RunLoop' has no member 'Mode'
>         RunLoop.current.add(timer, forMode: RunLoop.Mode.default)
>                                             ^~~~~~~ ~~~~
> ObjectiveC.NSObject:160:15: note: did you mean 'zone'?
>     open func zone() -> NSZone!
>               ^
> ObjectiveC.NSObject:162:21: note: did you mean 'zone'?
>     open class func zone() -> NSZone!
>                     ^
> Foundation.NSObject:4:21: note: did you mean 'pose'?
>     open class func pose(as aClass: Swift.AnyClass)
>                     ^
> Foundation.RunLoop:8:15: note: did you mean 'runMode'?
>     open func runMode(_ mode: RunLoopMode, beforeDate limitDate: Date) -> Bool
>               ^
> 
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	CompileSwift normal x86_64 /Users/michalborowski/Downloads/goxel-master 2/osx/goxel/goxel/AppDelegate.swift
> 	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
> (2 failures)

**Comment by guillaumechereau** [comment]
Might be because you have to update xcode to the last version.

**Comment by YarlBoro** [comment]
Oh, it is highly possible. I tried to compile it on my old MacBook, that can’t get anything beyond MacOS 10.12 & XCode 9.
I will try it later on my main rig.
Thanks for the tip!

**Comment by YarlBoro** [comment]
It compiled fine on latest XCode. 
Unlit mode works perfect. Once again, thanks!!!
