### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by dirkson** [guillaumechereau/goxel#134]
Hey there! I can't seem to figure out how to adjust alpha using Goxel 0.8.2.

The only UI features I can find that might do this are "Edit->Shift Alpha" and the "pick color" dropdown's direct hex editing.

If I adjust "Shift Alpha" by a positive or a negative value, the "alpha" reported by the color picker does not change, and I do not observe any difference in rendered alpha in the UI. Frankly, nothing seems to change. If I add two extra hex values to the "pick color" dropdown's hex code, they are immediately stripped upon hitting enter.

Am I missing something?

Cheers,
-Dirk

**Comment by guillaumechereau** [comment]
The 'shift alpha' option was actually for something totally different, and the name was very misleading.  I just removed this.

Now since the version 0.9.0, you should be able to adjust layer alpha by changing the material alpha value.
