### ISSUE TITLE
Build error on ubuntu

### ISSUE THREAD

**Issue by trsh** [guillaumechereau/goxel#137]
g++ -o src/imgui.o -c -std=gnu++11 -Wall -Wno-narrowing -Ofast -Werror -O3 -DNDEBUG -DHAVE_LIBPNG=1 -pthread -Isrc -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/inih -Iext_src/lua src/imgui.cpp
src/imgui.cpp:27:32: error: unknown option after ‘#pragma GCC diagnostic’ kind [-Werror=pragmas]
 #pragma GCC diagnostic ignored "-Wclass-memaccess"
                                ^~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
scons: *** [src/imgui.o] Error 1
scons: building terminated because of errors.
Makefile:8: recipe for target 'release' failed
make: *** [release] Error 2

**Comment by trsh** [comment]
:((

**Comment by guillaumechereau** [comment]
Can you try again now ?

**Comment by trsh** [comment]
Working. Thank you budy
