### ISSUE TITLE
GZDoom can't open .kvx file exported form Goxel

### ISSUE THREAD

**Issue by axredneck** [guillaumechereau/goxel#146]
How to reproduce:
- Download any .wad/.pk3 which contain voxels (e.g. [this](https://www.moddb.com/mods/reikalldoomvoxels))
- Extract any .kvx file from it (use Slade for .wad and 7zip for .pk3)
- Import this .kvx file to Goxel
- Export file back
- Put it back to .wad/.pk3 with Slade or 7zip
- Run .wad, e.g. `gzdoom -iwad DOOM2.WAD -file yourmod.pk3`

Tested with Goxel 0.8.3

**Comment by guillaumechereau** [comment]
Thanks for the report.  I just tested and it doesn't work indeed.  I will try to fix that.

**Comment by guillaumechereau** [comment]
I just pushed a few changes for better KVX export.  Not perfect yet, but I could make a small change to the armour model at least.

Do you know how to recompile goxel?  If not I could send you a new executable for testing.

![Screenshot from 2019-06-05 17-34-06](https://user-images.githubusercontent.com/107679/58946455-7d740b00-87b8-11e9-985a-aa9b45748050.png)
![Screenshot from 2019-06-05 17-33-15](https://user-images.githubusercontent.com/107679/58946461-81a02880-87b8-11e9-92f1-4852ac9baff6.png)

**Comment by YarlBoro** [comment]
Happy armour XD

I don't know about GZDoom, but latest changes sure improved KVX export for Build engine. Now it is possible to adjust offsets/pivots in Goxel. This is HUGE for animated objects, because with Goxel multiobject (layer) support, I can finally synchronise center point for multiple models (frames) with variable sizes...Great, thanks!

**Comment by guillaumechereau** [comment]
I think what I am going to do is set to the KVX pivo to the origin of the goxel image.  That way we can somehow adjust it by moving the image.

**Comment by axredneck** [comment]
I will try to compile and test current git master. I'm on Arch Linux, and there is `goxel-git` pkgbuild in AUR but it's another software with the same name "Goxel".

**Comment by axredneck** [comment]
Compiled, tested, works OK. Thank You!
