### ISSUE TITLE
scons debug=0 error 127

### ISSUE THREAD

**Issue by qinyt** [guillaumechereau/goxel#148]
When I use pacman to build on Windows, why do i get "scons debug=0 error 127" message ? I've installed all the requested packages in the discription. Any help

**Comment by DeathDealer33** [comment]
I can't build on Windows currently either. It just needs to be fixed by @guillaumechereau

**Comment by guillaumechereau** [comment]
You shouldn't use:

    scons debug=0

instead do:

    scons mode=debug

Or directly:

    make

Do you see any error message?  Can you past the log of what you see exactly?
