### ISSUE TITLE
Alpine linux error goxel-0.9

### ISSUE THREAD

**Issue by sodomon2** [guillaumechereau/goxel#149]
```
g++ -o goxel -fsanitize=address -fsanitize=undefined -pthread src/gui.o src/imgui.o src/tests.o src/marchingcube.o src/script.o src/procedural.o src/gesture.o src/palette.o src/goxel.o src/utils.o src/model3d.o src/tools.o src/mesh.o src/main.o src/system.o src/pathtracer.o src/box_edit.o src/material.o src/luagoxel.o src/mesh_utils.o src/layer.o src/action.o src/image.o src/shape.o src/mesh_to_vertices.o src/shader_cache.o src/camera.o src/quantization.o src/gesture3d.o src/render.o src/theme.o src/yocto.o src/assets.o src/gui/render_panel.o src/gui/export_panel.o src/gui/about.o src/gui/palette_panel.o src/gui/topbar.o src/gui/debug_panel.o src/gui/light_panel.o src/gui/menu.o src/gui/settings.o src/gui/material_panel.o src/gui/image_panel.o src/gui/view_panel.o src/gui/layers_panel.o src/gui/tools_panel.o src/gui/cameras_panel.o src/tools/plane.o src/tools/procedural.o src/tools/color_picker.o src/tools/laser.o src/tools/extrude.o src/tools/brush.o src/tools/selection.o src/tools/move.o src/tools/shape.o src/formats/txt.o src/formats/vox.o src/formats/voxlap.o src/formats/png_slices.o src/formats/gox.o src/formats/wavefront.o src/formats/povray.o src/formats/gltf.o src/formats/vxl.o src/formats/dicom.o src/formats/qubicle.o src/formats/png.o src/utils/img.o src/utils/gl.o src/utils/mustache.o src/utils/vec.o src/utils/json.o src/utils/ini.o src/utils/texture.o src/utils/sound.o src/utils/color.o src/utils/cache.o src/utils/b64.o -L/usr/local/lib -lasan -lubsan -lGL -lm -lz -lglfw3 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find libasan_preinit.o: No such file or directory
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lasan
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lasan
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lubsan
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lubsan
collect2: error: ld returned 1 exit status
scons: *** [goxel] Error 1
scons: building terminated because of errors.
diego [~/Descargas/goxel/goxel-0.9.0]$ 
```

**Comment by sodomon2** [comment]
Al crear el binario aparece este error ya le a pasado a algien o solo ami?

**Comment by sodomon2** [comment]
When creating the binary appears this error already happened to algien or just ami?

**Comment by sodomon2** [comment]
When creating the binary appears this error already happened to algien or just ami?

**Comment by guillaumechereau** [comment]
Currently goxel link with libasan and libusan in debug mode.  Maybe this should be optional if those are not present.  Can you try to install those libs on Alpine?  I use ubuntu so I cannot test that easily.

**Comment by sodomon2** [comment]
As far as I can see there's no bookstore with that name in alpine linux.

**Comment by guillaumechereau** [comment]
OK then I guess the scons script should check if they are available and only use them if that is the case.  Not sure how this should be done... any idea?

**Comment by sodomon2** [comment]
I don't know. I don't know much about C. I just lua and a little bit of C.

**Comment by sodomon2** [comment]
apparently when I run make release it gives me another kind of error

Here's the mistake.

lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/.../.../.../x86_64-alpine-linux-musl/bin/ld: /usr/local/lib/lib/libglfw3.a(x11_window.c.o): Indefinite reference to the 'XConvertSelection' symbol.
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/.../.../.../x86_64-alpine-linux-musl/bin/ld: //usr/lib/libX11.so.6: Error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
scons: *** Error 1.
scons: building finished due to errors.
do: ***[Makefile:8: release] Error 2
diego[~/Downloads/goxel/goxel-0.9.0]$

**Comment by sodomon2** [comment]
well here i have something amazing when i compile with make i get the above mentioned error 

but if I compile it with make release or make profile it compiles without error

**Comment by sodomon2** [comment]
> apparently when I run make release it gives me another kind of error
> 
> Here's the mistake.
> 
> lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lintl
> /usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/.../.../.../x86_64-alpine-linux-musl/bin/ld: /usr/local/lib/lib/libglfw3.a(x11_window.c.o): Indefinite reference to the 'XConvertSelection' symbol.
> /usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/.../.../.../x86_64-alpine-linux-musl/bin/ld: //usr/lib/libX11.so.6: Error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> scons: *** Error 1.
> scons: building finished due to errors.
> do: ***[Makefile:8: release] Error 2
> diego[~/Downloads/goxel/goxel-0.9.0]$

It was just a mistake to find the glfw3 library.

**Comment by guillaumechereau** [comment]
In release, we don't use libasan so it works yes.   Not sure about the glfw3 lib though...

**Comment by sodomon2** [comment]
I have a doubt that is when I compile with make release and the binary weighs 2 mb but change with make profile weighs 21 mb do you know what the reason?

**Comment by guillaumechereau** [comment]
Yes: in 'profile' the compiler adds debug symbols, so the binary takes more space.  It's normal.

**Comment by sodomon2** [comment]
Which would you recommend profile or release?

**Comment by guillaumechereau** [comment]
'Profile' is only for development, so you shouldn't use it for normal use.  If you just want to run goxel, compile in 'release'.

**Comment by sodomon2** [comment]
Thank you. You've been very helpful.

**Comment by sodomon2** [comment]
Well I'll close the issue but if I have more mistakes I'll reopen it.

**Comment by guillaumechereau** [comment]
OK cool! That would be nice.  Well in that case of course it should be compiled in 'release'!

**Comment by sodomon2** [comment]
Well I'll close the issue but if I have more mistakes I'll reopen it.

**Comment by sodomon2** [comment]
I have a little problem how do I put the prefixes?

**Comment by sodomon2** [comment]
try this 
make release PREFIX=/usr/
but it still installs in /usr/local/

**Comment by sodomon2** [comment]
diego [~/Descargas/goxel/goxel-0.9.0]$ sudo make install
install -Dm744 goxel /usr/local/bin/goxel
for size in 16 24 32 48 64 128 256; do
install -Dm644 data/icons/icon${size}.png \
        $(printf '%s%s' /usr/local/share/icons/hicolor/ ${size}x${size}/apps/goxel.png)
done
install -Dm644 snap/gui/goxel.desktop \
    /usr/local/share/applications/goxel.desktop
install -Dm644 \
    snap/gui/io.github.guillaumechereau.Goxel.appdata.xml \
    $(printf '%s%s' /usr/local/share/metainfo/ io.github.guillaumechereau.Goxel.appdata.xml)
diego [~/Descargas/goxel/goxel-0.9.0]$ sudo make uninstall

**Comment by guillaumechereau** [comment]
If you set the PREFIX env variable it should work.  It doesn't?

**Comment by guillaumechereau** [comment]
Should be more like:

    PREFIX=/usr/ make install

Something like that I guess.

**Comment by sodomon2** [comment]
diego [~/Descargas/goxel/goxel-0.9.0]$ sudo make install
install -Dm744 goxel /usr/local/bin/goxel
for size in 16 24 32 48 64 128 256; do
install -Dm644 data/icons/icon${size}.png \
        $(printf '%s%s' /usr/local/share/icons/hicolor/ ${size}x${size}/apps/goxel.png)
done
install -Dm644 snap/gui/goxel.desktop \
    /usr/local/share/applications/goxel.desktop
install -Dm644 \
    snap/gui/io.github.guillaumechereau.Goxel.appdata.xml \
    $(printf '%s%s' /usr/local/share/metainfo/ io.github.guillaumechereau.Goxel.appdata.xml)
diego [~/Descargas/goxel/goxel-0.9.0]$ sudo make uninstall

**Comment by sodomon2** [comment]
Thank you for your help again I already work the prefix

**Comment by sodomon2** [comment]
Here's the package I told you I'd do: https://gitea.com/Sodomon/Mis_APKBUILD

**Comment by sodomon2** [comment]
They're just packages for alpine linux.

**Comment by sodomon2** [comment]
I have another problem when I install of normal form but to execute me says:

diego [~/Downloads/goxel/goxel-0.9.0]$ goxel
bash: /usr/bin/goxel: Permission denied
diego [~/Downloads/goxel/goxel-0.9.0]$ 

If it continues like this I can not do the package and install the package and tells me the same thing

**Comment by guillaumechereau** [comment]
I am not sure about that.  You should probably ask other Alpine linux packagers how they do it.

**Comment by Johnnynator** [comment]
> Currently goxel link with libasan and libusan in debug mode. Maybe this should be optional if those are not present. Can you try to install those libs on Alpine? I use ubuntu so I cannot test that easily.

libsanatizer is not avaible for the musl libc, therefore you can't install asan/ubsan. Making it optional would be nice.

**Comment by sodomon2** [comment]
> I have another problem when I install of normal form but to execute me says:
> 
> diego [/Downloads/goxel/goxel-0.9.0]$ goxel
> bash: /usr/bin/goxel: Permission denied
> diego [/Downloads/goxel/goxel-0.9.0]$
> 
> If it continues like this I can not do the package and install the package and tells me the same thing

I already put the solution on it I had packed badly
