### ISSUE TITLE
Invisible cloned layer makes crash after "Merge visible"

### ISSUE THREAD

**Issue by jeyum2** [guillaumechereau/goxel#154]
Reproduce

1. Clone Layer 1
2. Set invisible to Layer 1.clone
3. Do Merge visible with Layer 1 and other layers
4. Set visible Layer 1.clone
- At this time, Layer 1.clone shows last voxels of Layer 1
- And  if you do something, Goxel will be crashed

I think it has to be `Uncloned` before running `Merge visible`

**Comment by guillaumechereau** [comment]
Thanks for the report!  There is a bug here indeed.

**Comment by guillaumechereau** [comment]
I think this is fixed by now.  Going to close this.
