### ISSUE TITLE
Overlap rules(drawing order) for editor and "Merge visible" are different

### ISSUE THREAD

**Issue by jeyum2** [guillaumechereau/goxel#155]
In editor, voxels in layer overlaps from top layer to bottom layer.
But when do `Merge visible`, it seems bottom layer to top layer.

For example

There are 3 layers in order and overlaps on same position.

```
Layer 1
Layer 2
Layer 3
```

Voxel of Layer 3 shows on top in editor.
But when do `Merge visible`,  voxel in Layer 1 shows on top.

**Comment by guillaumechereau** [comment]
I see.  Yes it probably makes sense to show the layers in the other order (new layers on top).  I'll check that.

**Comment by jeyum2** [comment]
<img width="752" alt="before merge" src="https://user-images.githubusercontent.com/776652/60782610-c25dd980-a18a-11e9-9fc9-fed7c8e2e02c.png">
<img width="752" alt="after merge" src="https://user-images.githubusercontent.com/776652/60782611-c25dd980-a18a-11e9-83c8-25591ec6dfcc.png">

For helping understanding, I have attached screenshots.

Before merge, the red voxels are shown in editor.
But the black voxels are remains after merge.

**Comment by guillaumechereau** [comment]
I just pushed a fix for that.  Should work better now.

**Comment by jeyum2** [comment]
It works 👍 
Thank you
