### ISSUE TITLE
Color doesn't export in any format except MagicaVoxel which has size limits

### ISSUE THREAD

**Issue by GoxelBug** [guillaumechereau/goxel#157]
I need to export with color so I can use it with other programs such as Blender and Godot.
You can keep color by exporting to MagicaVoxel but the MagicaVoxel size limit kicks in which is a deal breaker. Additionally, it is a tedious extra step. Thanks for your time.

**Comment by guillaumechereau** [comment]
Have you tried to export in 'ply' ? I just tried and it shows the color properly in blender.

**Comment by GoxelBug** [comment]
I tried again just barely and it did not show up for me in either Blender or 3D viewer. Perhaps I am doing something wrong or maybe I need to reinstall.?

**Comment by GoxelBug** [comment]
I checked something and I discovered information about ply files. I have to enable vertex colors to see the color. So I guess it was just my ignorance. Now I need to figure out how to convert the vertex colors into something else that is usable out of blender.
