### ISSUE TITLE
[Help] Can't find location of Palettes folder on Linux

### ISSUE THREAD

**Issue by TheMisteryMan** [guillaumechereau/goxel#160]
I'm running Goxel on my Arch Linux installation, and while I found the location for [mac](https://github.com/guillaumechereau/goxel/issues/44#issuecomment-319294032), I couldn't find any for Windows, or Linux.

I checked the usual suspect for Linux (`/home/YourUsername/.loca/share/ApplicationName`), but didn't find anything there.

**Comment by guillaumechereau** [comment]
I added the location in the settings for now.  On linux, this should be:

    ~/.config/goxel/palettes/

**Comment by TheMisteryMan** [comment]
Thanks, seems to work, save for the fact that the Palette titles aren't being displayed in the list.
