### ISSUE TITLE
'Image'>'Bounded' tickbox missing

### ISSUE THREAD

**Issue by YarlBoro** [guillaumechereau/goxel#165]
As in title, image bounding can't be switched off. Tickbox doesn't show up (MacOS).
I hope it can be fixed, thank you.

**Comment by guillaumechereau** [comment]
Ah yes I removed that, thinking that it wasn't very useful since we can just grow the box size as much as we want.  Do you really need that?

**Comment by YarlBoro** [comment]
Without it, it takes a lot of time to adjust bounding box after import. Especially if you try to put together many smaller pieces. Please bring back bounding box removal or maybe instead add option to automatically fit image/layer bounding box to all voxels. Thanks in advance!

**Comment by YarlBoro** [comment]
I noticed latest commit, thank you Guillaume!

**Comment by guillaumechereau** [comment]
You're welcome.  Let me know if that is enough.  If not we can think of something else, or eventually reintroduce the 'unbounded' mode.

**Comment by YarlBoro** [comment]
Feature that you added works nice, no troubles/bugs so far.
