### ISSUE TITLE
Issue, Bug, User Error?

### ISSUE THREAD

**Issue by Mickey-Wrenn** [guillaumechereau/goxel#169]
![Goxel Screen Shot 2019-09-04 at 9 54 36 AM (2)](https://user-images.githubusercontent.com/54899153/64262257-d0ff0d80-cefb-11e9-82ed-875fa2216774.png)
Hello. I am very new to Goxel, but I am enjoying it immensely. I've figured out pretty much everything I want to do with it, except for one issue. There are areas in my scene where I cannot use the Select-Clear tool to erase voxels. I've attached a JPEG that should illustrate my issue. For a workaround, I can move the layer to another area, clear the voxels, then move it back. For a while, I thought I was missing something with the borders/boxes, but I don't think that's it. I would appreciate any insights.

**Comment by guillaumechereau** [comment]
Looks like a bug.  Would you mind sending me the image by email so I can check it directly?

**Comment by Mickey-Wrenn** [comment]
Hi, Guillaume.
Thanks for your email. The screenshot is attached. Let me know if you need
anything else.
With kind regards,
~ Jamie


_____________________________________________________
Jamie R. Wildman
1139 Sixth St.
Bedford, IN, USA, 47421-2311
812.583.1959
