### ISSUE TITLE
Better looking user interface

### ISSUE THREAD

**Issue by guillaumechereau** [guillaumechereau/goxel#17]
I need to cleanup the current UI, find better icons, font, etc.

**Comment by YarlBoro** [comment]
Hello 

I've made some icons and partial mockup of brush tool panel (still WIP). It's not the best that world have seen, but maybe enough to start some discussion :)

I tried to make this UI proposition clear & sharp and scalable on both low res and high-res/"retina" displays. For type I used Roboto, main font of AndroidOS (it was really well designed, with scalability & readability and neutral aesthetics in mind).

I made two versions of UI, Dark and Light one. I got preference for dark UIs, but I know that some people (and jobs) got different needs. Maybe it wont be a bad thing to make two modes for UI from the beginning? On the other hand, it is more work each time something requires changing...

Color panel is very rough, just an quick attempt. I feel like some more functionality can be added (invert current color, add color to current palette, create new palette with this color?)

Those two icons on the side of toolbar (bucket & cursor inside selection) are just ideas for future tools:  
Fill Color - Classic bucket tool. Fill all connected pixels of the same color. 
Automatic Selection - something like PS magic wand, select all connected pixels of the same (similar?) colors. Complimentary to current cubic selection system.

![goxelui_ 2x](https://cloud.githubusercontent.com/assets/7037937/23076585/6c6da3c2-f541-11e6-83dc-6cd3cecb92f1.jpg)

**Comment by guillaumechereau** [comment]
Nice! Do you have the icons files in svg format? I could add them already for the next release.

**Comment by YarlBoro** [comment]
Thanks!
"I could add them already for the next release" - just great
Yes, I can export them in SVG. Will try to do that today.

**Comment by guillaumechereau** [comment]
I made a first commit with the new icons.
I had to tweak the files so that the icons still render OKish even at low resolution (32x32).
I am thinking that we could actually try even smaller, maybe something around 28x28.

![image](https://cloud.githubusercontent.com/assets/107679/23113734/10723f5c-f775-11e6-9a2a-e9d21968d480.png)

You can see the svg files in the 'svg' directory at the root of the project.

**Comment by YarlBoro** [comment]
28x28 - I agree, current UI seem to be a little bit oversized

In regard to tweaks, there should be no need to adjust those icons to look sharp in 32 px. This is half of their original size (64 pix) in Illustrator project, so they should scale perfectly. I used pixel snapping & simulating UI resolution of Goxel for this exact reason, strange. Probably SVG files that I sent you are scaled a little bit off comparing to Illustrator. That seem to cause blurriness and other problems during conversion. 
Quick solution - for time being - would be replacing png icon atlas with one exported straight from Illustrator, what do you think?

**Comment by YarlBoro** [comment]
It seems to be more complicated than I though, I'm reworking stuff.

**Comment by nureyev** [comment]
@YarlBoro I uploaded a PDF document with steps that might help. It's long to read, so here's the important bit :)

If you're using strokes for the icons, Illustrator will set it 'center' by default, but at smaller export sizes that means it's not pixel aligned. 

You can check this by going to the Edit\Preferences menu and clicking 'Use preview bounds' under 'General' settings. You should see the width and height of your icons change to from whole numbers to fractions (64.5 for example).

Changing the stroke to inner should fix the problem.

I hope it helps.

[Pixel Art in Adobe Illustrator.pdf](https://github.com/guillaumechereau/goxel/files/787989/Pixel.Art.in.Adobe.Illustrator.pdf)

**Comment by YarlBoro** [comment]
@nureyev I was not sure how to deal with this without some cumbersome steps.
That helps a lot, thank You! :)

**Comment by nureyev** [comment]
@YarlBoro No problem. If I can help with anything else let me know

**Comment by guillaumechereau** [comment]
I am thinking we should really make the icons smaller.
As a reference, blender icons (who look really good) are based on a 20x20 grid:
https://wiki.blender.org/index.php/Dev:2.5/Doc/How_to/Add_an_icon

**Comment by nureyev** [comment]
I resized the existing UI to see the difference. The icons are 20x20, the buttons are bigger. It's a way to check if usability is affected. The buttons at the smaller size are a bit small to click efficiently or quickly on a high resolution display, but other people may have other opinions.

There's obvious savings in space, but you may need to increase gaps between buttons to avoid mistakes when selecting tools?

<img width="210" alt="goxel_comparison" src="https://cloud.githubusercontent.com/assets/18418518/23156291/02f44dfc-f81f-11e6-9f41-5bd141c5b5e9.png">

**Comment by guillaumechereau** [comment]
Indeed.  I think the right spot would be smaller icons, with more or less the same spacing as now, but without the gray backgrounds on unselected icons.  I will try to make some mockups to see how it looks like.

**Comment by guillaumechereau** [comment]
An example:
![untitled](https://cloud.githubusercontent.com/assets/107679/23159594/57591488-f85e-11e6-9664-c10ddfcb76ca.png)

**Comment by nureyev** [comment]
That does look more consistent and less complicated. If the highlight has slightly more contrast, or is a different color, it's quite readable even without separate buttons.

**Comment by YarlBoro** [comment]
I like last mockup too and imho it is a huge improvement.

Should I adjust my icons to this new concept or You have something else in
mind, guys?

**Comment by guillaumechereau** [comment]
Well I will need a set of icons that can be rendered to a smaller size (pixel aligned). If you want you can have a try with your icons. With Inkscape I have some success by using a grid of a quarter of a pixel with a major line every pixel.  Then I use strokes size just slightly smaller than a pixel.  It seems to render nicely.  I made a few icons for a test of a fancier look.  Not sure if that is better than pure black&white though.
![untitled](https://cloud.githubusercontent.com/assets/107679/23166572/16663e10-f87c-11e6-8c2a-c93aef82dcb9.png)

**Comment by YarlBoro** [comment]
> I made a few icons for a test of a fancier look. Not sure if that is better than pure black&white though.
They sure look nice. I would reduce amount of gradients here & there, also use more uniform palette.
I'll make a mockup tomorrow based on Your work above.

**Comment by YarlBoro** [comment]
They sure look nice. I would just reduce amount of gradients and make palette more uniform.
I will prepare mockup tomorrow based on Your work above.

**Comment by nureyev** [comment]
I spent some time looking around for references since I'm not sure what style might work best. I found these two as examples. Both have all the icon types we might need, so we can use them as a reference to create our own and even new ones for future features. 

This is a flat style, but in color:
http://www.axialis.com/stock-icons/pure-flat-2013-toolbar.html

This has two styles, both monochrome. One is a thin, black and white 'line' style, the other a gray 'classic'.
http://www.iconbeast.com/

If these don't suit the look you want, let me know, I can look for a reference with more embossing, detail, shading and so on?

For interests sake I tested the icons:
![goxel ui test_iconbeast_line](https://cloud.githubusercontent.com/assets/18418518/23202362/481e1dc8-f8e6-11e6-8f9d-7eb96a1b1047.png)

![goxel ui test_iconbeast_classic](https://cloud.githubusercontent.com/assets/18418518/23202374/537a9084-f8e6-11e6-9674-da43b4d4dbc0.png)

![goxel ui test_axialis](https://cloud.githubusercontent.com/assets/18418518/23203431/26737c4a-f8eb-11e6-9341-eb04fff44659.png)

**Comment by guillaumechereau** [comment]
I am not sure what style is the best.  I would like to try both a set of black&white icons (similar to what yarlboro did) and a set of "fancier" icons like the ones I did.

Please don't use any non free licensed icons, even as references. Instead either look at references from other open source projects (there's plenty to look at), or just draw a few ones for testing.

**Comment by nureyev** [comment]
I've been working on something else so sorry for the delay. I tried a few different styles. Resampling icons with a lot of details creates quite a bit of antialiasing which looks fuzzy or blurry. I'm trying to figure out how to keep it clear at 32x32 pixels while creating the original at a much larger size. I tried a pixel art style with 16x16 pixel icons, which looks clear and readable but it might look too 'retro' or unprofessional. I don't know.

@YarlBoro might find this technique interesting. If you create a grid in Illustrator (grid tool) and use Live Paint you can 'paint' the icon almost like in Photoshop. The grid can be 32x32 or larger. Resampling/resizing to pixel aligned boundaries is not a worry because it's a bunch of squares.

**Comment by guillaumechereau** [comment]
I improved the general layout of the ui, with a better font and items.  This largely based on blender style.  Here is how it looks like now:

![screenshot from 2017-03-03 21-49-32](https://cloud.githubusercontent.com/assets/107679/23553360/60a7004a-005b-11e7-89ba-ec8ceb4adf2a.png)

The next step is to get smaller icons, and I think I will be good for a new release.

**Comment by YarlBoro** [comment]
That is looking really clean and elegant. I like it. Especially value
fields.

Here, same mockup but using new b&w tool icons:
[image: Inline images 1]

I took a lesson from my earlier mistakes, now all is pixel perfect. All
these icons fit module of 26 x 26 pixels. Tried 22 x 22, but it was too
little comparing to rest of UI.
What do You think, is this right direction?

If you accept it, I'll prepare mode & shape icons.

**Comment by YarlBoro** [comment]
Sorry for being so erratic in response, still not much free time.

Regards,
Michał

**Comment by YarlBoro** [comment]
Maybe smaller icons were better after all. On the left ones from before, on
the right reduced ones:
[image: Inline images 1]

**Comment by YarlBoro** [comment]
Even more compact version on the right:
![goxel_mockup_v6_02](https://cloud.githubusercontent.com/assets/7037937/23580074/dcdcb6f6-00fa-11e7-85bd-7ee7865ff161.png)

**Comment by guillaumechereau** [comment]
Yes it's very good like that, I think I like the smaller one better.  But the mode and shapes icons are still too large.  The best format for me would be a single svg file with all the icons in a grid.  Then I'll write a script to use inkscape to export them one by one as binary.

**Comment by YarlBoro** [comment]
> But the mode and shapes icons are still too large.

 yes, now they are adjusted to the rest:
![goxel_mockup_v6_05](https://cloud.githubusercontent.com/assets/7037937/23580716/f60ef3f8-0106-11e7-81a7-25a5b130896e.png)

Svg file with all the icons in a grid - ok, I'll prepare it soon

**Comment by guillaumechereau** [comment]
Thanks!

**Comment by YarlBoro** [comment]
No problem :)

[Goxel_IconGrid_v1.zip](https://github.com/guillaumechereau/goxel/files/818811/Goxel_IconGrid_v1.zip)


Inside archive:
png - how it suppose to look like :)
svg - there are sixteen 32 x 32 px fields, grid is 1 pixel wide

**Comment by guillaumechereau** [comment]
OK thanks, I'll have a look at it as soon as I can.

**Comment by guillaumechereau** [comment]
I will probably have to redraw the file in Inkscape as I did before though, since the export from illustrator really makes it hard to modify the icons.

**Comment by YarlBoro** [comment]
If it is about strokes that are converted to fills, I did it on purpose. I can bring them back tomorrow.

**Comment by guillaumechereau** [comment]
Yes if you can.  I would prefer to have the source file in a format that can be edited by anybody.  By the way please, add a GPL licence text to the file in a layer, so that people can freely modify it.  You can check the blender svg icons file as a reference, I think they did it pretty well.

**Comment by YarlBoro** [comment]
Hello
I could not take care of icons earlier. It was not as simple, as I thought that it is going to be (as usual:)).
Both Illustrator CC 2017 & Affinity Designer, that I use, are not handling SVG format in a same way. Designer is a LOT better in this regard, to be frank, but there are some differences anyway when I compare files. I have hard time making file easily editable and keeping proper appearance at the same time. Probably 'user error', but I'm not really used to working with vectors in this manner. 

Looked into Blender icons as you suggested. 
I put this information inside of icon file, is it what You asked for? 
"This content is subject to the GNU GPL license, which accompany it along with copyright info" 

Here is new SVG file with license info & two icons with strokes brought back (color select & laser tool):

[Goxel_IconGrid_v1_02.svg.zip](https://github.com/guillaumechereau/goxel/files/852445/Goxel_IconGrid_v1_02.svg.zip)

**Comment by TomWor** [comment]
Hi, I've been reading this thread and just wanted to mention I liked the first mockup with the darker background and light icons best, especially because there are not much visible outlines around the buttons and the inverted icon colors appear a little easier to read.
I'd also vote for a little more space around the icon graphics on the buttons to "let them breath" a little.
Also: On a larger monitor, the different tool panes accessible via the tabs on the right are all quite empty at the bottom, I could imagine they would work great in an accordion fashion, so the user could fold out several and have them stacked on one another.

**Comment by guillaumechereau** [comment]
What I will try to do soon is allow to have different themes, possibly stored in config files.
I hope I can make a first draft of this next week.

**Comment by guillaumechereau** [comment]
I just added an experimental theme editor (edit -> settings).
For the next release I would like to support two theme, one dark and one light.  For the moment we can also use the theme to change the button size, though I am not sure I will keep this.

**Comment by guillaumechereau** [comment]
OK I just release the version 0.7.0, there is a setting menu, from which we can chose between the default and dark theme.  It is undocumented, but we can also add themes in the user directory and they will be available as well.
