### ISSUE TITLE
Setup Travis CI for build AppImage (portable binary package for Linux)

### ISSUE THREAD

**Issue by ghost** [guillaumechereau/goxel#171]
Setup Travis CI for auto-build *AppImage* (portable package for Linux) for each commit:

0. Create `.travis.yml` - https://github.com/OpenVSP/OpenVSP/blob/master/.travis.yml
1. https://github.com/appimage/AppImageKit
  1.1. https://github.com/probonopd/linuxdeployqt
  1.2 https://github.com/linuxdeploy
2. https://github.com/probonopd/uploadtool
3. Enable Travis CI pushing to GitHub releases for this repo.

For example, take a look on *LeoCAD* `.travis.yml` implementation:

- https://github.com/leozide/leocad/blob/master/.travis.yml

And here is what resulted builds would look like:

- https://github.com/leozide/leocad/releases/tag/continuous

For any support:

- https://docs.appimage.org/user-guide/faq.html#question-where-do-i-get-support

**Comment by guillaumechereau** [comment]
Closing: I switch from Travis to GitHub CI system.
