### ISSUE TITLE
[Bug/Improvement][macOS] Too high mouse sensitivity when zooming

### ISSUE THREAD

**Issue by ThatIsAPseudo** [guillaumechereau/goxel#178]
Fisrtly, I'm on macOS Mojave 10.14. When I zoom in or out, the zooming step is way too high so the camera always goes kilometers away from the workspace with a single scroll tick. I tried on several displays with different DPI, with a mouse and with the built-in touchpad, the zoom keep messing.
I guess it is not a hardware issue, since my material works fine otherwise.

I suggest to add a "mouse sensitivity" setting, since the software is absolutely not usable as it stands. By the way, the online version ~~works perfectly~~ is very sensitive as well,but much less than the desktop one.

**Comment by guillaumechereau** [comment]
Thanks for letting me know.  I will have a look, I guess a setting would work, but I rather fix the issue so that the default works properly.

**Comment by guillaumechereau** [comment]
I pushed a fix for this.  Should be working in the next release.
