### ISSUE TITLE
Where is documentation?

### ISSUE THREAD

**Issue by ragnarov** [guillaumechereau/goxel#179]
Hi,
First of all awesome.
Awesome piece of software you have built.
Now I can't understand all the tools that are provided by the sidebar.
Maybe they are self explanatory but I don't understand all of them.
I also can't find documentation.
Help please :)

Edit:
Another thing I wanted to add is that I am not an artist and this is the first time I am using Voxel.
I mean I did not know this could be done like this.
I only knew about Blender.

**Comment by guillaumechereau** [comment]
Yes some documentation really needed.  I don't have time right now to do it, since that is quite a lot of work, but that is something I would like to work on at some point.  I think the best for now is that you ask me directly if you have some particular issue.

**Comment by GmrLeon** [comment]
Would it be viable to open a wiki tab here on Github that folks could fill out with documentation (which you could correct occasionally, if needed)? As I've learned about Goxel, I've mainly been using Weaving of Smoke's YouTube videos to help, but even these have shown themselves rapidly outdated in some respects, lol

**Comment by guillaumechereau** [comment]
Yes why not, I never checked this feature of github.  I was thinking when I write documentation it would be in markdown format so that I can generate some html pages but also a pdf version of it.   Would the github wiki support something like that?

**Comment by guillaumechereau** [comment]
I just created a wiki.  Feel free to edit it if you want to contribute, it should be open at the moment.
