### ISSUE TITLE
Missing option to change layer bounding box size

### ISSUE THREAD

**Issue by BrunoSupremo** [guillaumechereau/goxel#181]
Hi, this is while using the debug version you gave for that other problem with the software not working on amd.
Each layer has a bounding box. This box is used by the game I'm modding to animate the models. It basically uses the center of the bounding box as the coord position of that layer.
This mean that if, for example, a 3x3x3 cube is extended by 1 voxel to the left (now a 4x3x3 bounding box) its center is shifted with it. So what I would do was edit the bounding box and extend it to the other side too (now a 5x3x3 bounding box) to get its center into the same coord as before.
The bug report here is that we do not have a way to do that anymore, to edit the bounding box sizes.
In the image example below, I selected the head layer of the model. If I were to add some decoration to his left ear, the bound box would extend to fit the new voxels, I then would extend it manually to the right side too to keep it centered.
![image](https://user-images.githubusercontent.com/16531876/71755758-106a4600-2e6b-11ea-8b0e-1bba068ad831.png)

**Comment by guillaumechereau** [comment]
OK I see.  Yes it seems that there is a bug somewhere that makes the UI not show the bounding box resizing widget.  I will have a look at that.

**Comment by guillaumechereau** [comment]
Should be fixed now.  I'll make a new release soon for this and a few other recent fixes.
