### ISSUE TITLE
Feature request - shortcut keys for subtract and add

### ISSUE THREAD

**Issue by therealrobster** [guillaumechereau/goxel#193]
Hi there,

The two most tools I find myself using are subtract and add.

I can't find any shortcut keys but it would save me SO much mouse travel if I could just hit for example Q and W (or whatever is close to each other) and work faster.

I hope this suggestion helps.

**Comment by guillaumechereau** [comment]
Hello,

If you maintain the space bar pressed it should toggle between those two modes.  Doesn't it work?

**Comment by therealrobster** [comment]
It does yes!  Thank you.
