### ISSUE TITLE
Wrong buttons label?

### ISSUE THREAD

**Issue by VeskoRadic** [guillaumechereau/goxel#194]
Is there wrong label on buttons for layers movement? As you can see in attached image, when I press "UP" layer goes down and vice versa.
![goxel](https://user-images.githubusercontent.com/63882439/79618052-4de89b80-8109-11ea-8ef8-689c88e4d7c9.gif)

**Comment by sariug** [comment]
:D Interesting, mine is the same. No one said anything up until now :D

**Comment by guillaumechereau** [comment]
It's a bug.  Will fix that as soon as I get the time to work on goxel again.

**Comment by guillaumechereau** [comment]
Should be fixed now.
