### ISSUE TITLE
How to move selected voxels?

### ISSUE THREAD

**Issue by iperov** [guillaumechereau/goxel#198]
subj

**Comment by guillaumechereau** [comment]
Currently the way is to cut the selection into a new layer, move it, and then merge it back.  Really not optimal I agree.

**Comment by LanceJZ** [comment]
There is no cut though. You basically can't.

**Comment by guillaumechereau** [comment]
In the 'selection' tool options, there is a 'cut as new layer' button.  Not in the top menu (maybe should be added there indeed).
