### ISSUE TITLE
On Archlinux, ASan runtime does not come first.

### ISSUE THREAD

**Issue by BSanchez** [guillaumechereau/goxel#2]
When I try to run, The program die with this error : 

> ==9523==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.

I'me on a up-to-date Archlinux.

**Comment by guillaumechereau** [comment]
Hi, as a quick fix, you can remove the asan lines in SConstruct.

On Monday, 5 October 2015, SANCHEZ Benjamin <notifications@github.com>
wrote:

> When I try to run, The program die with this error :
>
> ==9523==ASan runtime does not come first in initial library list; you
> should either link runtime to your application or manually preload it with
> LD_PRELOAD.
>
> I'me on a up-to-date Archlinux.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guillaumechereau/goxel/issues/2>.
>


-- 
Sent from my iPad.

**Comment by guillaumechereau** [comment]
I just committed a possible fix: 2ce0456

**Comment by mnlangston** [comment]
Fix worked for me on Manjaro

**Comment by guillaumechereau** [comment]
OK great.  I guess it should work for all distros now.  I am closing this issue.
