### ISSUE TITLE
GlTF export broken for Blender as well as Godot

### ISSUE THREAD

**Issue by nanderv** [guillaumechereau/goxel#207]
Hi,

When exporting the gox file supplied, the resulting file cannot be imported in Blender, nor can it be imported in Godot.

Blender says something about a material index being out of bounds, Godot refuses to import.

**Comment by guillaumechereau** [comment]
Hello.  What version of goxel are you using?  In the glTF export options (in the export tab) there are two settings for vertices color or texture.  Which one are you using?

**Comment by guillaumechereau** [comment]
Should be fixed for godot at least in the last release.
