### ISSUE TITLE
Make Goxel ensure saved files have the .gox extension

### ISSUE THREAD

**Issue by unfa** [guillaumechereau/goxel#214]
Often when I save my work I type in the name and forget about adding the .gox extension, as most software ensures the correct extension is present when a file format is known.

Goxel doesn't do that, saving files under names without any extension, which are later not shown in the File Open dialog.

I need to add the .gox extension to my file, and only then Goxel will see the files it has saved before.

**Comment by guillaumechereau** [comment]
Should be fixed now I think.
