### ISSUE TITLE
Seperate Colors into layers

### ISSUE THREAD

**Issue by Ryder17z** [guillaumechereau/goxel#218]
Since the layers currently seem bugged, it seems like it would be a better idea to use colors then seperate the colors into different layers, however i do not see such a function in goxel.

**Comment by guillaumechereau** [comment]
What is the bug with the layers?

**Comment by Ryder17z** [comment]
1. draw something in a new instance of goxel
2. duplicate the layer
3. subtract some pieces
4. switch layer, hiding previous layer
5. delete some pieces on this layer
6. attempt to switch back to the previous layer
7. goxel partially stops working.

**Comment by guillaumechereau** [comment]
I'll have a look!

**Comment by Ryder17z** [comment]
![image](https://user-images.githubusercontent.com/2000703/104736546-6db5fa00-5743-11eb-9f5c-1c7c44638c2e.png)

After picking "edge" channel it updated to 10.7 and the issue is less of a problem but i can still trigger it. (creating a new layer fixes the problem temporarily - this wasn't the case on 10.4)
