### ISSUE TITLE
Canvas size?

### ISSUE THREAD

**Issue by Ryder17z** [guillaumechereau/goxel#219]
XYZ should all be possible to change independently.

**Comment by guillaumechereau** [comment]
It isn't?

**Comment by Ryder17z** [comment]
i couldn't find a way to change the canvas size.

**Comment by diegopau** [comment]
@Ryder17z in the "Image" tab (on the left panel) you can set size for each of the axis independently, this changes the canvas size. Can you confirm that this is what you were asking for and maybe this issue can be closed?

**Comment by Ryder17z** [comment]
D'oh. Yes. I didn't notice that tab

Still, a setting for default size should exist
