### ISSUE TITLE
Procedural rendering language documentation

### ISSUE THREAD

**Issue by ZhekaS** [guillaumechereau/goxel#22]
I see the feature as the most interesting part of this software, but unfortunately I haven't found any description of the language used and it's features. Any plans to document it?

**Comment by guillaumechereau** [comment]
Hi ZhekaS,

I wrote a very basic tutorial about the syntax:
https://blog.noctua-software.com/goxel-procedural.html

No real doc for the moment unfortunately, but if you have any question or feedback about the procedural rendering, feel free to comment on this issue.

**Comment by ZhekaS** [comment]
Sure, thanks. Is there a link to the blog from the project page? I haven't seen one. Perhaps it would be a good idea to put it.

**Comment by guillaumechereau** [comment]
It was there, but I changed the website to jekyll, and I think the link got remove by mistake. I will put it back.

**Comment by SteveBaker** [comment]
I would have preferred something like (say) Python bindings.  Inventing a whole new language seems like overkill.
