### ISSUE TITLE
Windows Version Goxel 0.10.7 not showing filemenu anymore and options menu is shown incorrectly

### ISSUE THREAD

**Issue by nlsvdb** [guillaumechereau/goxel#222]
I have a problem with the Goxel 0.10.7 Windows Version not showing the filemenu anymore and options menu is shown incorrectly.
See screenshot. Goxel 0.10.6 works fine.
My computer:
Windows 10 home, Version 2004
Intel Core I5
NVIDIA GT 730 2 GB, with latest driver update
![Knipsel](https://user-images.githubusercontent.com/66520890/102655961-7252b700-4173-11eb-9d8d-8d0ab054f124.PNG)

**Comment by guillaumechereau** [comment]
Thanks for the report.  Not sure what's wrong.  I just checked and it seems to work for me with windows 10.  Do you by any chance know how to compile goxel?

**Comment by nlsvdb** [comment]
I don't know how to compile the source files of goxel.
My computer is 64Bit.
For me it seems like a code problem to corrupt the layout of goxel.
I know goxel is compiled with python.
I have the python runtime  version 2.7.13 and python version 3.8.2(32Bit) and a python launcher 3.8.6994.0 installed on my computer.
Could that be the problem of conflicting with goxel?
The newest Blender version 2.91( 64Bit ) works fine though, but I know that comes with his on python files version.

**Comment by nlsvdb** [comment]
Update: 
I removed python runtime 2.7.13 and replaced it with python version 3.91 (64Bit), but the layout of goxel stays corrupted.
Though, I think a found the possible problem
In goxel 0.10.6 a file is automatic generated 
imgui.ini
[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][Goxel]
Pos=0,0
Size=1536,844
Collapsed=0

In goxel version 0,10.7 the settings are automatic changed to values
[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][Goxel]
Pos=0,0
Size=1920,1055
Collapsed=0

My screen has a maximum resolution of 1920 x 1080 with scale setting of apps at 125%.
That could possible explain why the layout of goxel doesn 't fit and shows corrupted.
When I change the file  imgui.ini with the settings of version 0.10.6, Goxel overrules this settings automatic to the default size of 1920,1055. in version 0.10.7.

I think when goxel is using by default the same settings as in version 0.10.6 the problem could be solved.
Can you fix this?

**Comment by nlsvdb** [comment]
I have solved the problem without having to change my scale settings by going to goxel and select properties and go to DPI settings and change this to system value. 
Goxel version 0.10.7 now works fine again.  
PROBLEM SOLVED!!!
