### ISSUE TITLE
How to import PC Goxel file to iOS device such as iPad?

### ISSUE THREAD

**Issue by transformcube** [guillaumechereau/goxel#227]
I have some PC version Goxel .gox files and wanted to edit them in my iPad, is there any methods can do the trick? thanks

**Comment by guillaumechereau** [comment]
If you have a Mac, you should be able to see goxel data file when you connect your iPad to it.  You can then copy your files into it.

Not so sure how to do that without a Mac computer thought.

Let me know if that doesn't work.

**Comment by transformcube** [comment]
Thanks you for the promptly reply.  I can transfer the files to iPad but they can't open using Goxel due to the files lack of MIME type (Mac) associated with Goxel apps.

**Comment by guillaumechereau** [comment]
I see.  I am not sure how to best fix that.  Would be nice if someone with more Mac experience could help here.

**Comment by transformcube** [comment]
Thank you for your concern, seems like it may some hints.
Associating Your App with File Extension/Mime Type on iPhone (iOS), Android & Windows
https://www.codenameone.com/blog/associating-your-app-with-file-extension-mime-types-iphone-android-windows.html
