### ISSUE TITLE
Segfault using "see back"

### ISSUE THREAD

**Issue by Charles-the-Cat** [guillaumechereau/goxel#23]
Immediately after checking the "see back" box under advanced render settings, the application crashes with this message:

```
** (goxel:30609): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
[1]    30609 segmentation fault  ./goxel
```

**Comment by guillaumechereau** [comment]
This might be an opengl shader bug.  Unfortunately I won't have much time to work on goxel these days. I'll try to check it out as soon as I can.

**Comment by guillaumechereau** [comment]
I just had a look, and it turned out to be a simple fix.  Should work now in the master git branch.
