### ISSUE TITLE
Intel Graphics Error

### ISSUE THREAD

**Issue by Angell1993** [guillaumechereau/goxel#234]
I've encountered an error on an Intel APU, in the embedded Intel Graphics driver..
No tools inside the Goxal app..
With AMD it works but for some reason not with Intel Graphics..

On Windows 10..

**Comment by 24wuw** [comment]
another piece of evidence that amd is better than intel :)

**Comment by guillaumechereau** [comment]
Sorry I am not sure to understand.  What is the issue exactly?
