### ISSUE TITLE
Cannot open .vox file

### ISSUE THREAD

**Issue by hellocatfood** [guillaumechereau/goxel#237]
I have this voxel model of a photo which I converted to a .vox file using this script https://github.com/Zarbuz/FileToVox/
[cat.zip](https://github.com/guillaumechereau/goxel/files/6183876/cat.zip)

The model opens fine in Magicavoxel as seen below 
![Screenshot from 2021-03-22 16-41-32](https://user-images.githubusercontent.com/151947/112026829-802b2600-8b2e-11eb-9db5-96b331da08f6.png)

When I try to import it into Goxel all of the regions are arranged in a weird way.
![Screenshot from 2021-03-22 16-40-37](https://user-images.githubusercontent.com/151947/112026870-89b48e00-8b2e-11eb-9083-e0285ece9100.png)

Is there any way to fix this?

**Comment by guillaumechereau** [comment]
Thanks for the report.  Must be something wrong in the import code.  I'll have a look at it.

**Comment by guillaumechereau** [comment]
Could you send me the vox file?

**Comment by hellocatfood** [comment]
Hi. The file is in the first post (listed as cat.zip)

**Comment by guillaumechereau** [comment]
OK got it.  I can reproduce the bug with it.

**Comment by guillaumechereau** [comment]
I think I got a fix.  It seems like I did transpose the rotation matrix of vox format.

![image](https://user-images.githubusercontent.com/107679/112335744-7274cc80-8cf7-11eb-9208-6f6b8048c432.png)

I am going to push a fix.

**Comment by hellocatfood** [comment]
Brilliant, thanks for your quick response
