### ISSUE TITLE
.vxl files alpha issue

### ISSUE THREAD

**Issue by yusufcardinal** [guillaumechereau/goxel#238]
Good day,

maps imported directly from AoS in .vxl format use the alpha channel to draw shadows in-game. This means a lot of them are culled when imported in goxel. The program should disregard the alpha channel when importing AoS maps.

![image](https://user-images.githubusercontent.com/79484931/114599621-55ca1580-9c61-11eb-890a-50c1f72f5bcd.png)

Here's the same map, ran through a script that set all the alpha channels to 0x80:

![image](https://user-images.githubusercontent.com/79484931/114599668-68dce580-9c61-11eb-969a-1e1f23e0c35b.png)

**Comment by yusufcardinal** [comment]
Seems to be the same problem as issue #159

**Comment by yusufcardinal** [comment]
It seems that, for the time being, duplicating the layer fixes the issue.

Thank you Nuceto for pointing it out <3

**Comment by guillaumechereau** [comment]
Do you have an example of file that doesn't work?
