### ISSUE TITLE
More strict compiler on linux got errors

### ISSUE THREAD

**Issue by othelarian** [guillaumechereau/goxel#24]
When compiling, I had error about misleading indentation in ext_src/stb/stb_image.h. This is not a real error, but it's pretty obvious : in this file, you use defines to create case with "for" clause with one line instruction, but the compiler can't figure it out with the combine case-for and the last break instruction in the same line.

I corrected the file by adding brackets around the single instruction for the "for" instruction.
There is three block of these:
* line 1360
* line 4090
* line 4100

**Comment by othelarian** [comment]
[the gist with the patch](https://gist.github.com/othelarian/b9ce9fac66c8f4d8f333cc8dc178c7a1)

**Comment by guillaumechereau** [comment]
Thanks, I will apply this.
Since the bug comes from the stb libraries, you might want to send the same patch to the author:
https://github.com/nothings/stb

**Comment by guillaumechereau** [comment]
Technical question: how do I merge a gist into the repo while maintaining authorship?

**Comment by othelarian** [comment]
I think the best way will be using pull request, but it's ok if you don't mention my name, I'm glad to help you, it's enough for me. I'm working on a voxel editor too, but in Qt, and your repo is a great source of inspiration, so it's like a share: your knowledge, my patch ;) .

**Comment by guillaumechereau** [comment]
I know how to merge a branch, but I don't see how it works with gist...
Well, I'll apply the patch manually and add your name in the comment and AUTHORS file.

Good luck for your own editor.  I guess Qt would make the UI better looking. I considered it as well, but nothing I have seen so far beats imgui in term of simplicity.
