### ISSUE TITLE
Headless rendering

### ISSUE THREAD

**Issue by ebr** [guillaumechereau/goxel#241]
Is it possible to use `goxel` for headless rendering? I'd like to offload rendering to a cloud instance, as my laptop is too underpowered. I understand I could install a complete desktop environment and run a GUI instance of `goxel` remotely that way, but a more lightweight, CLI-only solution would be ideal. Many thanks!

**Comment by guillaumechereau** [comment]
Good question.  At the moment the only option is to use the '--export' option from command line, but this is quite limited.
