### ISSUE TITLE
Menus hidden, mouse offset when Windows display is scaled

### ISSUE THREAD

**Issue by jean-philippe-martin** [guillaumechereau/goxel#242]
Goxel thinks that the mouse cursor is about 10cm away from where the real cursor is and the top-left side of the interface is hidden. This makes navigating the menus extremely difficult.

To reproduce:

- In Windows 10, open the Start menu and go to "Settings"
- Select the "Display" tab
- Under "Scale and layout", "Change the size of text, apps, and other items" choose 150%
- Start goxel

Expected: the program is usable
Actual: most of the interface is hidden, mouse clicks go about 10cm away from where the mouse cursor is.

**Comment by PWhughes32** [comment]
Happy to find this, same exact thing is happening to me except the entire canvas seems to be off 10cm and along with the cursor being off. Only two icons appear in the task bar for me and they do not see to do anything when clicked.

Just downloaded Goxel and am not sure if there are any quick fixes or if I am doing anything wrong. Attached is an image of what I am seeing.

<img width="954" alt="Goxel Issue" src="https://user-images.githubusercontent.com/29695333/118414056-5d614d80-b657-11eb-85a2-fd7da67725a6.PNG">

**Comment by jean-philippe-martin** [comment]
@PWhughes32 you're not doing anything wrong. There is a workaround (until the software is fixed): set your Windows scaling to 100%.

**Comment by guillaumechereau** [comment]
OK, I think this is probably a simple bug, but I would need to get a high res window computer to try it one.

**Comment by guillaumechereau** [comment]
I'll close cause I think this is fixed in last release.  Feel free to reopen if the problem persists.
