### ISSUE TITLE
Mesh is sideways when importing into Blender or Minetest

### ISSUE THREAD

**Issue by brylie** [guillaumechereau/goxel#244]
I exported a mesh from Goxel 0.10.7 in obj format. 
![image](https://user-images.githubusercontent.com/17307/119852858-58828080-bf18-11eb-8715-c2696f4552ba.png)

Then when I import it into Blender, the mesh is sideways:
![image](https://user-images.githubusercontent.com/17307/119852931-67693300-bf18-11eb-8438-702ea5e4f9f4.png)

Likewise, the mesh is sideways when I import it into Minetest:

![image](https://user-images.githubusercontent.com/17307/119853437-e0688a80-bf18-11eb-83ab-ca87b00ba8ec.png)

Is there some setting where I can configure the axes at least when exporting the mesh?

**Comment by bztsrc** [comment]
> Is there some setting where I can configure the axes at least when exporting the mesh?

You could try [mtsedit](https://gitlab.com/bztsrc/mtsedit/). You can convert GOX files into MTS schematics with correct rotation out-of-the-box. It also provides a minimalistic GUI where you can rotate schems as you wish around any axes. You can load MTS files into Mitetest world with the MTSEdit, Handle Schematics, Worldedit, Schematic Editor etc. add-ons.

Cheers,
bzt

**Comment by guillaumechereau** [comment]
Is this bug still true in the last version of Goxel?  I cannot reproduce it.
