### ISSUE TITLE
Warn of unsaved file on exit

### ISSUE THREAD

**Issue by hellocatfood** [guillaumechereau/goxel#246]
Can a warning be added if a file is about to be closed without changes being saved? Currently if a user closes a file without saving (either via File > Quit or Alt + F4) the program will just close with no warning. 

Although users *should* be saving regularly a warning could prevent accidental losses.

**Comment by hellocatfood** [comment]
I've just seen that #236 addresses this. Can it be merged?

**Comment by guillaumechereau** [comment]
Right, I didn't realize a PR was made for that.  I will check it out.

**Comment by guillaumechereau** [comment]
I ended up writing a simpler implementation of the same feature.

**Comment by hellocatfood** [comment]
ok great, I'll try it out!

just fyi there's a PR which I think addresses the obj exporting request if you haven't seen it

**Comment by hellocatfood** [comment]
Works great, thanks

**Comment by hellocatfood** [comment]
I've just tried this again and it appears to be warning of unsaved changes even if I've just saved a document

**Comment by Black-Cat** [comment]
https://github.com/guillaumechereau/goxel/pull/236/files#diff-32b44c14f3e115731766a82eda708503fa162f9be89a98891fc1d63dcfbf1e80L729-L733
https://github.com/guillaumechereau/goxel/pull/236/files#diff-32b44c14f3e115731766a82eda708503fa162f9be89a98891fc1d63dcfbf1e80L748-L751

this changes should fix warning for saved documents

**Comment by guillaumechereau** [comment]
You are sure there is this problem?  How do you reproduce it?

**Comment by hellocatfood** [comment]
Yes, definitely. Steps to reproduce:

* Open goxel
* Make a new drawing
* Press Ctrl + S or File > Save to save for the first time
* Make more changes to the drawing
* Press Ctrl + S or File > Save to save
* Make no other changes and press Alt + F4 or File > Quit to exit goxel
* the unsaved changes dialogue will still appear

**Comment by hellocatfood** [comment]
I did a short recording of the issue so you can see it in action

https://user-images.githubusercontent.com/151947/124617704-0e71b080-de6f-11eb-83c4-956c8570e551.mp4

**Comment by guillaumechereau** [comment]
OK I see.  It happens after the second save.. I don't really understand the code of the PR you linked.  To me it seems that the bug is that the image 'save_key' is not properly updated.  I'll look into that.

**Comment by guillaumechereau** [comment]
OK my last commit should fix that.  Hopefully without any regression...

**Comment by hellocatfood** [comment]
Seems to work! I'll reopen again if I notice anything wrong.

@Black-Cat did you PR do anything different?

**Comment by Black-Cat** [comment]
no, same fix and there are no more differences except cosmetic ones
