### ISSUE TITLE
Visual indicators of document saved status

### ISSUE THREAD

**Issue by hellocatfood** [guillaumechereau/goxel#247]
Some software including GIMP, Blender and Inkscape have a visual indication in the application's title bar that a document is unsaved. They do this by showing an asterisk next to the document name i.e.

GIMP
![Screenshot from 2021-07-06 13-02-19](https://user-images.githubusercontent.com/151947/124597380-525aba80-de5b-11eb-875a-227d8c77cadf.png)

Inkscape
![Screenshot from 2021-07-06 13-09-25](https://user-images.githubusercontent.com/151947/124597448-6b636b80-de5b-11eb-9a3d-43469ca94d52.png)

Blender
![Screenshot from 2021-07-06 13-02-56](https://user-images.githubusercontent.com/151947/124597402-5be42280-de5b-11eb-8ef4-ebc8562267fd.png)

In goxel this isn't shown so from goxel itself there isn't a way to know if your current document is saved. Can the asterisk in the title bar be implemented?

Additionally, it might be useful to show when a document has been saved in the status bar at the bottom. Here's how Inkscape and GIMP do it once a document is saved:

![a](https://user-images.githubusercontent.com/151947/124597732-b8dfd880-de5b-11eb-8895-1a60fba98ac5.png)

![Screenshot from 2021-07-06 13-09-25](https://user-images.githubusercontent.com/151947/124597620-9948b000-de5b-11eb-886e-ae032b9eb2aa.png)

**Comment by guillaumechereau** [comment]
Yes that would be a nice addition!

**Comment by guillaumechereau** [comment]
I pushed a commit for this.
