### ISSUE TITLE
Color Picker keyboard shortcut only working with lower case "c"

### ISSUE THREAD

**Issue by hellocatfood** [guillaumechereau/goxel#248]
The keyboard shortcut for the colour picker "C" doesn't work. If I manually set the keyboard shortcut to be a lower case "c" it will work only for lower case "c". Other keyboard shortcuts ("r" for region, "b" for brush) work if the upper or lower case letter is pressed.

Tested on #dfac379 on Ubuntu 21.04

**Comment by guillaumechereau** [comment]
I just fixed that.  Thanks!

**Comment by hellocatfood** [comment]
Thanks, works great. And thanks for addressing these issues so quickly
