### ISSUE TITLE
Android build

### ISSUE THREAD

**Issue by thebiblelover7** [guillaumechereau/goxel#249]
Hi! I wanted to try goxel on Android but didn't find a way to build it. 

Is it not open source? Or how can I build it instead?

**Comment by thebiblelover7** [comment]
@guillaumechereau Any ideas?

**Comment by guillaumechereau** [comment]
The wrapper code to make goxel work on android is not open source at the moment no.  I could open it all maybe at some point though, why not.

**Comment by thebiblelover7** [comment]
@guillaumechereau Great! Let me know if I could help in anything. I would love to test it, etc.
