### ISSUE TITLE
Please store imgui.ini in XDG_CONFIG_HOME/goxel or in $HOME/.config/goxel, not directly in $HOME

### ISSUE THREAD

**Issue by xyproto** [guillaumechereau/goxel#250]
Hi,

Thanks for creating Goxel, it's very fun to use.

When starting Goxel on Arch Linux, it creates `imgui.ini` in the `$HOME` directory. Placing stray files directly in `$HOME` is generally frowned upon.

Please store `imgui.ini` in a suitable location like `$XDG_CONFIG_HOME/goxel` or `$HOME/.config/goxel` instead.

Best regards,
Alexander F. Rødseth

**Comment by guillaumechereau** [comment]
Thanks for letting me know.  In fact I think we shouldn't store this file at all.  I will see how to disable it.

**Comment by guillaumechereau** [comment]
I just pushed a fix for that.
