### ISSUE TITLE
VirtualBox: Goxel does not run in Windows VM

### ISSUE THREAD

**Issue by calousar** [guillaumechereau/goxel#255]
Goxel version: 0.10.8
VirtualBox Version: 6.1.16
Host: Ubuntu 20.10
Guest VM: Windows 10 Pro (Version 20H2)

![VirtualBox_Windows 10_25_09_2021_00_19_06](https://user-images.githubusercontent.com/91358125/134756309-b84b52c6-d8ff-4246-a53e-db3513fe1338.png)

It appears to be an OpenGL issue, but I'm not sure how to fix it. Other 3D applications like the Unity game engine run just fine under the same setup.

How to get this working?

**Comment by guillaumechereau** [comment]
Really not sure about that, I rarely use Windows or VM.  If you know how to compile you could try to compile goxel in debug mode on your guest OS and see if there are some errors that show at runtime.
