### ISSUE TITLE
Feature request: hide / show all layers

### ISSUE THREAD

**Issue by niklr** [guillaumechereau/goxel#262]
Is it possible to hide/show/toggle all layers at once? This feature would be really handy!

**Comment by pegvin** [comment]
The original other doesn't seem much active so I'll be working on [goxel2](https://github.com/pegvin/goxel2), and I added this feature too, I would be glad if you tried it.

**Comment by guillaumechereau** [comment]
@nikl: you can do shift click on a layer view icon to toggle all the other layer visibility.  That should be close to what you want to do I guess.
