### ISSUE TITLE
Dropping Linux support?

### ISSUE THREAD

**Issue by brylie** [guillaumechereau/goxel#264]
Out of curiosity, are you planning on dropping Linux support? I just noticed there isn't a Linux build in the latest release and the Downloads page lists only Mac and Windows desktop environments.

I've been hoping for a bug fix that was resolved some months ago in https://github.com/guillaumechereau/goxel/issues/243

I saw the recurring bug with glfw-wayland as well https://github.com/guillaumechereau/goxel/issues/224, and wonder if those types of bugs might be contributing to the lack of Linux build.

**Comment by guillaumechereau** [comment]
Thanks for reminding me.  I forgot to attach a linux build in the last release, I will do it now.  No plan to drop Linux support, in fact I almost mostly work on Linux.
