### ISSUE TITLE
Zooming too far out of frame causes project to disappear

### ISSUE THREAD

**Issue by Boellis** [guillaumechereau/goxel#266]
Im using GOXEL version 0.10.8 on Windows. The project works fine until I zoom far out(originally an accident, recreated in a separate project) and am unable to zoom back in/out to get back to my work area. Any ideas on how to show my work area again?

**Comment by guillaumechereau** [comment]
Right, there should be a button to recenter the camera.  I'll look into that when I get the time.

**Comment by guillaumechereau** [comment]
I made a commit so that View -> Default reset the camera distance to fit the image.
