### ISSUE TITLE
Can't import Color material in Unity3D

### ISSUE THREAD

**Issue by shohan4556** [guillaumechereau/goxel#27]
Hi, I made a simple map using goxel and exported as **.obj** file but when I import the file in **Unity3D** the **colors** of the map which I used inside goxel editor did not imported in Unity.

**Comment by guillaumechereau** [comment]
I just pushed a change that add color information in the obj file by
adding the rgb values after the 'v' lines.

As far as I can tell this is not standards, so I am not sure if unity3d
support it.

An other solution could be to use ply if unity supports it.

**Comment by shohan4556** [comment]
Unity dont support ply format, any alternative way available.

**Comment by TechnoPrometheus** [comment]
Wvefront obj added? great! nice job, Goxel grows well! as soon as I have time, I compile the source.

In the version of Windows, it had to include the extension of the file export (eg mymodel.vox). I intension to make videos of yt, to give the right visibility to this very nice software. Thanks so much.
