### ISSUE TITLE
facing direction?

### ISSUE THREAD

**Issue by Shadowblitz16** [guillaumechereau/goxel#276]
Can we have a block bench like icon for which way is north?
![image](https://user-images.githubusercontent.com/2453707/165393081-9e0e7559-6068-431d-839f-bc78accc950d.png)

**Comment by pegvin** [comment]
![image](https://user-images.githubusercontent.com/75035219/179397601-150b0a81-d1fd-4aaa-8921-fc8b801aa94f.png)

there's a gizmo in bottom left.
