### ISSUE TITLE
where is goxel palettes saved on linux?

### ISSUE THREAD

**Issue by Shadowblitz16** [guillaumechereau/goxel#277]

**Comment by guillaumechereau** [comment]
Hello,

The exact location depends if the env variable XDG_CONFIG_HOME is set.  If it is set, then we use:
 `$XDG_CONFIG_HOME/goxel/palettes`, if not, then it default to `~/.goxel/palettes/`.

For example on my machine running ubuntu, I got the palettes in `~/.config/goxel/palettes/`

**Comment by Shadowblitz16** [comment]
ok ty
