### ISSUE TITLE
Program don't started

### ISSUE THREAD

**Issue by maxtar** [guillaumechereau/goxel#278]
When try to start in console got an error:
./goxel-0.10.8-linux: error while loading shared libraries: libglfw.so.3: cannot open shared object file: No such file or directory

**Comment by EZRAIDv2** [comment]
Same

**Comment by maxtar** [comment]
@EZRAIDv2 this command install from repository. Need to add them?

**Comment by jackoboDev** [comment]
> When try to start in console got an error: ./goxel-0.10.8-linux: error while loading shared libraries: libglfw.so.3: cannot open shared object file: No such file or directory

True solution according to my Linux experience : 
sudo apt-get install libglfw3 : for classic use
sudo apt-get install libglfw3-dev : for development use

The command "sudo apt install goxel" will not install maybe the latest version of the program on some linux OS

**Comment by pegvin** [comment]
glfw is not installed for some reason, you can install it via:

On Debian & it's children:
```bash
sudo apt-get install libglfw3
```

On Arch & it's children:
```
yay -S glfw3
```

**Comment by guillaumechereau** [comment]
Closing because I think the issue is not in goxel itself.
