### ISSUE TITLE
[Request] Adding a Homebrew cask

### ISSUE THREAD

**Issue by DaSlang** [guillaumechereau/goxel#290]
**Request**
Making the latest version of Goxel available through [Homebrew](https://brew.sh/).

**Notes**
Does adding a Homebrew cask sounds like a good idea? 
If so I can create a pull request in the Homebrew repo and add a cask pointing to the latest released version of Goxel.

This would be the cask code
```ruby
cask "goxel" do
  version "0.11.0"
  sha256 "4877eb6dad13fcccd6816f599312d6a1619634458c69c8465a1cf7cef0d675c1"

  url "https://github.com/guillaumechereau/goxel/releases/download/v#{version}/goxel-#{version}-mac.zip",
      verified: "https://github.com/guillaumechereau/goxel"
  name "Goxel"
  desc "Open Source Voxel Editor"
  homepage "https://goxel.xyz/"

  app "Goxel.app"

  zap trash: [
    "~/Library/Application Support/Goxel",
    "~/Library/Preferences/com.noctuasoftware.goxel.plist",
    "~/Library/Saved Application State/com.noctuasoftware.goxel.savedState",
  ]
end
```

**Comment by guillaumechereau** [comment]
Hello DaSlang.  Would be great yes!  Let me know if there are any change required in the code to make it easier.

**Comment by DaSlang** [comment]
Just created a [pull request](https://github.com/Homebrew/homebrew-cask/pull/129964) in the Homebrew repo. 

I'll keep you posted on the results 😄

**Comment by DaSlang** [comment]
The cask has been merged! 🎉

With the latest version of Homebrew, the command `brew install --cask goxel` should install Goxel v0.11.0.

Whenever a new version get released, it's sufficient to maintain the cask by pointing to the latest .zip package on Github and updating the version number and the SHA checksum.

**Comment by guillaumechereau** [comment]
Nice!  I'll check it out later on my mac.
