### ISSUE TITLE
Render in ortho view?

### ISSUE THREAD

**Issue by kyaso** [guillaumechereau/goxel#295]
I just discovered Goxel, and it's a gift to have this powerful tool available for free!

My question: is there a way to render a scene in ortho/isometric view?

**Comment by pegvin** [comment]
Goto "Camera" Tab -> Select "Ortho" Checkbox

**Comment by kyaso** [comment]
@pegvin Thanks, however, this only changes the camera for the editing mode. I am talking about rendering. For me, the "Ortho" mode seems to be ignored in render mode. Am I missing something?

**Comment by pegvin** [comment]
> Am I missing something?

yes you are, you are not actually doing what i'm saying, the above steps i showed work with render mode too.

**Comment by kyaso** [comment]
Interesting, then it looks like a bug. Because in my case, the render ignores the ortho selection.

I'm running the latest version on Linux.

**Comment by pegvin** [comment]
interesting.

**Comment by guillaumechereau** [comment]
Yes the code handling this case was missing.  I added it now.  Thanks for pointing this out.
