### ISSUE TITLE
Image to mesh has multiple problems

### ISSUE THREAD

**Issue by thelabcat** [guillaumechereau/goxel#296]
I'm trying to convert an image sprite to a mesh. However, when I import the image, it is offset by 0.5 voxels on the X axis:
![image](https://user-images.githubusercontent.com/53358500/191146431-393d5ffc-4638-44bb-a196-9615a56e4130.png)
![image](https://user-images.githubusercontent.com/53358500/191146347-3f37d9ca-5b20-4835-b995-1daf50f334cd.png)
When I convert the layer to mesh, it spreads out on the Y axis with gaps, and doubles over on the X axis:
![image](https://user-images.githubusercontent.com/53358500/191146573-601723ec-7839-48e3-9e94-4b6fa2114715.png)
My suspicion for the second error is an iteration mistake, though the first one may not be related.

**Comment by guillaumechereau** [comment]
Seems like a bug, might be due to the fact that your image has an odd width.  If that is the case a workaround would be to add a transparent 1 pixel column to your image.

**Comment by thelabcat** [comment]
Thanks. Will try that.

**Comment by thelabcat** [comment]
I tried again with a new image of only even dimensions. While the offset is now fixed, the spacing and squash-doubling still happened.

**Comment by guillaumechereau** [comment]
I just pushed a fix for the offset bug.  I couldn't reproduce the spacing bug though.  Can you recompile from source to try it out with the current version?

**Comment by thelabcat** [comment]
I generally have had bad experiences trying to compile things myself. Is there another way?

**Comment by thelabcat** [comment]
Recompiled, the bugs are fixed. The spacing bug seems to be a result of the Flatpak being too old.

**Comment by guillaumechereau** [comment]
OK good to hear!
