### ISSUE TITLE
Minor issue with verion label

### ISSUE THREAD

**Issue by avekir** [guillaumechereau/goxel#297]
Minor issue

If to download 0.11 release version and chech version via "Help" menu it says 0.10.8 instead of 0.11

![image](https://user-images.githubusercontent.com/6302833/192635090-a07d274b-6fd4-4065-981a-bddac8910c07.png)

**Comment by guillaumechereau** [comment]
Yes that is strange, normally this is supposed to be set automatically. I guess I didn't clean the project before building the release.  Should be fixed by the next release.
