### ISSUE TITLE
.gox file format specifications

### ISSUE THREAD

**Issue by benmoran56** [guillaumechereau/goxel#30]
Great program!

Do you have any plans to release the .gox file format specifications?

**Comment by guillaumechereau** [comment]
Hello Benjamin,

For the moment the only specification is the comment at the top of the
file `src/save.c`.  It slightly inspired by png.

If you want to support gox files in your own software I can eventually
write a proper doc.

**Comment by benmoran56** [comment]
Thanks for pointing that out. I'll have a look at the file. I would like to add support for .gox files to my project at some point, since it's easier to work with a single file instead of obj + mtl files. 

If you have time in the future, a proper document would be great!

**Comment by jjpepper** [comment]
Windows and Linux... I found the description in gox.c now.  https://github.com/guillaumechereau/goxel/blob/master/src/formats/gox.c  :-)

**Comment by jjpepper** [comment]
By the way, are you aware of atomontage engine?

**Comment by guillaumechereau** [comment]
Ah sorry I misunderstood your last question.  OK you got it now.  I just checked atomontage.  Looks interesting indeed.  I was thinking of adding support for dynamic level of details in goxel, so that we can have arbitrarily large scene with arbitrarily detailed objects inside, but that's something more interesting in a game engine that in an editor I think.

**Comment by dirkson** [comment]
gox.c appears to support materials now, but the "File format, version 2" comment at the top of the file doesn't mention them. Could I ping you to update the documentation for me?

**Comment by guillaumechereau** [comment]
Going through the old issue and seeing this one was left hanging.  Sorry there is still no proper documentation for goxel format for now.  My take on this is that eventually goxel should ditch this clumsy format and switch to gltf with just some extension to support volume clouds.
