### ISSUE TITLE
How to export with color?

### ISSUE THREAD

**Issue by Bits360** [guillaumechereau/goxel#307]
Unlike magicavoxel, no texture or color palette is exported for obj or any other format. Is this tool effectively useless, due to automatically losing color data on export? Or am i missing something?

**Comment by guillaumechereau** [comment]
Normally if you export in glTF the colors should be saved as a texture, or if you select the option as vertex color data.

**Comment by Bits360** [comment]
Im only getting mesh data (.gltf/.obj/.whatever) on v0.11.0, no texture, or any mention of one on the console.

**Comment by Bits360** [comment]
I have found that its a texture in a mesh file, which i didnt even know existed until now. Please consider adding support for separate texture export as .png, as some engines do not support importing png in mesh.

**Comment by guillaumechereau** [comment]
Yes this is currently not supported for the obj export.  Maybe I'll add it, but if you use gltf it should work doesn't it?

**Comment by Bits360** [comment]
Its fixed now, but this question was asked in 2022, since vox import was fixed since, i am probably going to transition to this, instead of dealing with magicavoxel much longer.
