### ISSUE TITLE
Add keybinds to all tools

### ISSUE THREAD

**Issue by Te3Que** [guillaumechereau/goxel#312]
After trying the program, I found it to be a good editor. The only thing I continue to find annoying is the lack of key bindings to say:
The Add, Sub and Paint function. As well as the extrude tool.
See this as a request to add a feature.

**Comment by guillaumechereau** [comment]
Currently maintaining space pressed toggles from add to sub, but there is no key to actually change the value.  What keys do you think would be the best for that?

**Comment by Te3Que** [comment]
#### If you look at something like MagicaVoxel, it uses **T** for add and **R** for subtract. In addition, it uses **V** for "brush" and **F** for faces or extrude. Now Goxel already have a adequate binding for brush but the rest is lacking for the power users.
---
* **T** for Add
* **R** for remove/ subtract
* **V** / B for brush
* **F** for faces/extrude

**Comment by guillaumechereau** [comment]
OK I added those shortcuts as default.

**Comment by Te3Que** [comment]
Cool, hopefully it will help others trying out Goxel coming from a different voxel editor. Do close the issue if you have either implemented or not, my request.
