### ISSUE TITLE
Vertex colors don't work properly on UnrealEngine 5

### ISSUE THREAD

**Issue by jerobarraco** [guillaumechereau/goxel#314]
Hello, nice software.
I have an issue where the vertex colors on unreal engine 5 are not directly usable. i have to modify them like color -.5 / .5 to get something that resembles the original color but yet it looks very bad. 
i tried tonemapping hdr, srgb and linear and nothing. it has a very weird scale.

pd: i know i can use the texture method, but i want to use vertex colors.

**Comment by guillaumechereau** [comment]
Does it work with the texture method?  To me it seems that the issue is of linear/sRGB.  Goxel exports the vertex color in sRGB but maybe it should be in linear indeed.

**Comment by jerobarraco** [comment]
like i said, textures works but is not useful to me.
screens

this is how it looks at the moment, but i had to do a special material to do it and the colors look just bad.
notice is unlit. also sorry is hard to position correctly
![image](https://github.com/guillaumechereau/goxel/assets/3729895/9027a027-8504-403e-b8f1-2c7d6e2d50b1)

this is the transformation i need to apply
![image](https://github.com/guillaumechereau/goxel/assets/3729895/293cb403-e51b-4ed6-9b9b-5da3c2d18623)

this is in goxel
![image](https://github.com/guillaumechereau/goxel/assets/3729895/3484b6d5-155f-4cd7-ae3e-3392350a7324)


this is the palette im using
https://lospec.com/palette-list/atari-8-bit-family-gtia

this are the gox and gltf files 
[Palette.zip](https://github.com/guillaumechereau/goxel/files/12114576/Palette.zip)

**Comment by guillaumechereau** [comment]
Are you using the last release?  Maybe you can try with the current nightly build version available here:

https://github.com/guillaumechereau/goxel/actions/runs/5609710977

**Comment by jerobarraco** [comment]
tried that one, crashes unreal.

**Comment by guillaumechereau** [comment]
I think one of the issue is that currently the texture generated by goxel uses a single pixel per voxel color, and it does not work well with unreal engine.  I think I will try to use a larger area by pixel, see if it improves the situation.

**Comment by guillaumechereau** [comment]
OK I think that fixed it, at least with a little test model I used:

![image](https://github.com/guillaumechereau/goxel/assets/107679/4b58da72-860c-43f1-8984-ef31ce439ab0)

**Comment by jerobarraco** [comment]
hey sorry i forgot to update this.
im using ue 5.3 now, 
i think there were some issues with 5.2 the new builds but on 5.3 works well. and the colors are exported correctly.
ive been using buid #72 and today i used #88 and they seem to be working fine.
https://youtube.com/live/Z7WWzGsPobU
