### ISSUE TITLE
Triangle count is super high

### ISSUE THREAD

**Issue by jerobarraco** [guillaumechereau/goxel#315]
When importing a simple object to unreal i noticed that the triangle count is very very high. even for simple objects.
it seems to me that there is no optimization being done when exporting.

**Comment by guillaumechereau** [comment]
Yes this is an issue at the moment.  It would be nice to integrate a mesh optimization step in the export code, maybe there are open source libraries doing that?

**Comment by jerobarraco** [comment]
i hope there are. i would bet there might be. specially since your code seem to be C. 
I think vengi/voxedit did something similar.

on a similar not. not sure if i should open a new ticket:
some of the triangles overlap with each other and result in some kind of Z fighting. 
this is a problem when using Nanite on unreal. the light renders with problems. also has issues due to overrendering (forgot the word).

**Comment by jerobarraco** [comment]
i found this one has c and cpp interfaces. https://meshoptimizer.org/

**Comment by jerobarraco** [comment]
i tried the utility called gtlfpack unfortunately it does some weird stuff to the gltf (like putting part of it in a bin file).
and unreal does not recognizes the format. 
 i tried using gltf glb and all the flags individually and together.

i would really like to ask if you do implement some optimization to have it as a export flag so i can turn it off/on depending on the asset to avoid issues like this and others.

**Comment by guillaumechereau** [comment]
The glTF export definitively needs more work.  I already changed the code a bit to at least use a single mesh per layer, but for the moment this is still using several primitive per mesh.

Meshoptimizer looks interesting yes.

Can you open a new issue specifically about the overlap you see?  If possible with a screenshot because I am not sure what the issue is.

**Comment by jerobarraco** [comment]
thanks a lot.
meshoptimizer seems promising. though unreal does not imports it as is. i needed to use the flag -noq otherwise it fails to import.
https://github.com/zeux/meshoptimizer/issues/584
if you ever implement this please make it optional or add a way to set the flags to ensure compatibility. it could make the tool unusable for me if i can't import.

it reduced the number of vertices but not the number of triangles

org
![image](https://github.com/guillaumechereau/goxel/assets/3729895/ef992a65-80da-4b9e-97c6-f99f40cc56c3)

packed
![image](https://github.com/guillaumechereau/goxel/assets/3729895/3ca4c919-fab7-4a03-99a7-2d09f8f5697b)

though something better should be out there..
unreal auto lod seems to get it around 500 each. but it's really annoying to set it up every time i import a mesh (which includes when i'm modifying it)
![image](https://github.com/guillaumechereau/goxel/assets/3729895/5f0ba21e-9045-44e9-a209-4b72777b2cab)

**Comment by jerobarraco** [comment]
on another news the overlapping vertices seems to be an issue with ue auto lod :/ ( i will open a new issue if i do find is something related with goxel)

lod 0
![image](https://github.com/guillaumechereau/goxel/assets/3729895/e89d0e2f-84a3-408f-86f5-00cfbef76796)

lod3 (the one i use as the default)
![image](https://github.com/guillaumechereau/goxel/assets/3729895/2342fca5-c924-4012-85c3-22c56e06f295)

**Comment by guillaumechereau** [comment]
I just pushed a first change that uses meshoptimizer to cleanup the mesh a little before export.  For the moment this is not doing any advanced simplification, but should already result in better topology.  Not sure if that would improve the import in UE though.

**Comment by guillaumechereau** [comment]
Also added an new option to simplify the mesh.  With simplification Goxel will attempt to remove as many vertices as possible before exporting.  All of this is still quite experimental.

**Comment by jerobarraco** [comment]
awesome! I will try them both whenever i get the chance :) Thanks a lot!

**Comment by jerobarraco** [comment]
As i feared the "simplify" option messes with the colors. 
this is with the simplify option
![image](https://github.com/guillaumechereau/goxel/assets/3729895/42dd2f9d-29e1-4b08-b656-15627053c79e)
![image](https://github.com/guillaumechereau/goxel/assets/3729895/b3b4faac-f0b2-49c3-9291-bee811369f40)


this is without it but with build 68
notice that the vertex and triangle count is exactly the same
![image](https://github.com/guillaumechereau/goxel/assets/3729895/750373d4-431c-48e0-b01d-d267e65649d8)
![image](https://github.com/guillaumechereau/goxel/assets/3729895/b3ec8b90-e044-4fcd-8b23-e16dc879b14e)

both of the above uses texture mode since vertex colors still crashes ue.

this is build 51 without the material set just for vertex count comparison
![image](https://github.com/guillaumechereau/goxel/assets/3729895/67021fff-8c97-481a-bcdc-debbadb45f9e)

**Comment by guillaumechereau** [comment]
Sorry for the late reply. Do you have the gox image? I am looking at this again but I cannot reproduce the issue currently.

**Comment by jerobarraco** [comment]
i think is this one. sorry the delay.
[Char18-Head.g.zip](https://github.com/guillaumechereau/goxel/files/13814439/Char18-Head.g.zip)

**Comment by guillaumechereau** [comment]
OK I made some changes to try to fix this bug.  Seems to work on your model, when I open it with blender.
I also change the "simplify" from a checkbox to a float input from 0 to 1, so that we can control the algo a bit. 

![image](https://github.com/guillaumechereau/goxel/assets/107679/fda23cc5-1720-4916-a49b-0cba8bbd777d)

**Comment by jerobarraco** [comment]
if this is in i will test it right away! thanks! 
though in that image bottom right of the right eye has a quirk.

**Comment by guillaumechereau** [comment]
Ah that's right, I didn't see that... I'll check a bit more.

**Comment by jerobarraco** [comment]
btw, the triangle count has definitely improved with the new simplification. thanks a lot!

**Comment by guillaumechereau** [comment]
Thanks.  I was unable to reproduce the quirk in the eye.  I wonder if my screenshot was maybe using the wrong export.  Do you still see the issue?

**Comment by jerobarraco** [comment]
i haven't seen this lately. if i come across it i'll open a new thread to not clog this ticket which seems to be a different issue.
i did had trouble with some meshes butchering the colors (as if the triangles were simplified too much), but i'll report back if i find it happening on the latest build.

**Comment by jerobarraco** [comment]
![Screenshot_20241019_174751](https://github.com/user-attachments/assets/f68efec9-54c6-47f0-9a39-b0b4ee4a5ad0)
![Screenshot_20241019_174845](https://github.com/user-attachments/assets/cea13c33-9ad7-479e-a106-eb0f9b813492)

this seems to be working pretty well on 1.51 thanks a lot!
i feel really uncomfortable closing the issue. but i assume that's what you'd prefer.

**Comment by jerobarraco** [comment]
the triangle count is much better now. i haven't seen the issue with the quirky eyes on 1.51.
i'll test for https://github.com/guillaumechereau/goxel/issues/336 soon when i can.

thanks a lot !
