### ISSUE TITLE
rpmlint error : E: missing-call-to-setgroups-before-setuid 

### ISSUE THREAD

**Issue by ilmanzo** [guillaumechereau/goxel#319]
while packaging this software on openSUSE, I got an error from rpmlint:

```
goxel.x86_64: E: missing-call-to-setgroups-before-setuid /usr/bin/goxel
This executable is calling setuid and setgid without setgroups or initgroups.
This means it didn't relinquish all groups, and this would be a potential
security issue.
```

this potential security issue seems introduced by the [quickjs external dependency](https://github.com/guillaumechereau/goxel/blob/8324c39ae1abc827c737678fd0e9a7bcbb1c33ed/ext_src/quickjs/quickjs-libc.c#L2978). 

I wish to understand if it's a real security problem or just a false positive; thanks

**Comment by guillaumechereau** [comment]
Thanks for letting me know.  I'll see how to fix that.

**Comment by guillaumechereau** [comment]
I pushed a fix that calls setgroups(0, NULL), though I am not really sure about it.  This is part of quickjs and I am not really sure what this function is doing exactly.  If this doesn't break anything I'll leave the fix like that for now.

**Comment by ilmanzo** [comment]
Thank you for the quick fix, now I included the patch, and the rpmlint message is gone. From a simple run test, the program seems working good!
