### ISSUE TITLE
Disregard if i'm a big dummy

### ISSUE THREAD

**Issue by Te3Que** [guillaumechereau/goxel#320]
Trying to build/compile the src installed the msys2 mingw64 and installed the packages needed.

System:
Win 10
ddr4 8gb
Intel i5 6600k

error while compiling:
src/../ext_src/quickjs/quickjs-libc.c:25:10: fatal error: grp.h: No such file or directory
   25 | #include <grp.h>
      |          ^~~~~~~
compilation terminated.
scons: *** [src/quickjs.o] Error 1
scons: building terminated because of errors.
make: *** [Makefile:8: release] Error 2

whole terminal dump:
$ make release
scons mode=release
scons: Reading SConscript files ...
Checking for C library libpng... no
scons: done reading SConscript files.
scons: Building targets ...
gcc -o ext_src/glew/glew.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer ext_src/glew/glew.c
ext_src/glew/glew.c: In function '_glewStrSame1':
ext_src/glew/glew.c:256:29: warning: the comparison will always evaluate as 'true' for the pointer o
perand in '*a + (sizetype)i' must not be NULL [-Waddress]
  256 |     while (i < nb && (*a)+i != NULL && b+i != NULL && (*a)[i] == b[i]) i++;
      |                             ^~
ext_src/glew/glew.c:256:44: warning: the comparison will always evaluate as 'true' for the pointer o
perand in 'b + (sizetype)i' must not be NULL [-Waddress]
  256 |     while (i < nb && (*a)+i != NULL && b+i != NULL && (*a)[i] == b[i]) i++;
      |                                            ^~
ext_src/glew/glew.c: In function '_glewStrSame2':
ext_src/glew/glew.c:272:29: warning: the comparison will always evaluate as 'true' for the pointer o
perand in '*a + (sizetype)i' must not be NULL [-Waddress]
  272 |     while (i < nb && (*a)+i != NULL && b+i != NULL && (*a)[i] == b[i]) i++;
      |                             ^~
ext_src/glew/glew.c:272:44: warning: the comparison will always evaluate as 'true' for the pointer o
perand in 'b + (sizetype)i' must not be NULL [-Waddress]
  272 |     while (i < nb && (*a)+i != NULL && b+i != NULL && (*a)[i] == b[i]) i++;
      |                                            ^~
ext_src/glew/glew.c: In function '_glewStrSame3':
ext_src/glew/glew.c:288:29: warning: the comparison will always evaluate as 'true' for the pointer o
perand in '*a + (sizetype)i' must not be NULL [-Waddress]
  288 |     while (i < nb && (*a)+i != NULL && b+i != NULL && (*a)[i] == b[i]) i++;
      |                             ^~
ext_src/glew/glew.c:288:44: warning: the comparison will always evaluate as 'true' for the pointer o
perand in 'b + (sizetype)i' must not be NULL [-Waddress]
  288 |     while (i < nb && (*a)+i != NULL && b+i != NULL && (*a)[i] == b[i]) i++;
      |                                            ^~
At top level:
cc1.exe: note: unrecognized command-line option '-Wno-unknown-warning-option' may have been intended
 to silence earlier diagnostics
cc1.exe: note: unrecognized command-line option '-Wno-unknow-pragma' may have been intended to silen
ce earlier diagnostics
gcc -o src/action.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/action.c
gcc -o src/assets.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/assets.c
gcc -o src/box_edit.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/box_edit.c
gcc -o src/camera.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/camera.c
gcc -o src/file_format.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/file_format.c
gcc -o src/formats/gltf.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/formats/gltf.c
gcc -o src/formats/gox.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/formats/gox.c
gcc -o src/formats/minetest.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/formats/minetest.c
gcc -o src/formats/png.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/formats/png.c
gcc -o src/formats/png_slices.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/formats/png_slices.c
gcc -o src/formats/povray.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/formats/povray.c
gcc -o src/formats/qubicle.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/formats/qubicle.c
gcc -o src/formats/qubicle2.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/formats/qubicle2.c
gcc -o src/formats/txt.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/formats/txt.c
gcc -o src/formats/vox.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/formats/vox.c
gcc -o src/formats/voxlap.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/formats/voxlap.c
gcc -o src/formats/vxl.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/formats/vxl.c
gcc -o src/formats/wavefront.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/formats/wavefront.c
gcc -o src/gesture.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/gesture.c
gcc -o src/gesture3d.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/gesture3d.c
gcc -o src/goxel.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/goxel.c
g++ -o src/gui.o -c -std=gnu++17 -Wall -Wno-narrowing -Wno-attributes -Wno-unused-variable -Wno-unused-function -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/gui.cpp
gcc -o src/gui/about.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/gui/about.c
gcc -o src/gui/app.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/gui/app.c
gcc -o src/gui/cameras_panel.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/gui/cameras_panel.c
gcc -o src/gui/debug_panel.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/gui/debug_panel.c
gcc -o src/gui/export_panel.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/gui/export_panel.c
gcc -o src/gui/image_panel.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/gui/image_panel.c
gcc -o src/gui/layers_panel.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/gui/layers_panel.c
gcc -o src/gui/light_panel.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/gui/light_panel.c
gcc -o src/gui/material_panel.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/gui/material_panel.c
gcc -o src/gui/menu.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/gui/menu.c
gcc -o src/gui/palette_panel.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/gui/palette_panel.c
gcc -o src/gui/quit.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/gui/quit.c
gcc -o src/gui/render_panel.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/gui/render_panel.c
gcc -o src/gui/settings.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/gui/settings.c
gcc -o src/gui/tools_panel.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/gui/tools_panel.c
gcc -o src/gui/topbar.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/gui/topbar.c
gcc -o src/gui/view_panel.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/gui/view_panel.c
gcc -o src/image.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/image.c
g++ -o src/imgui.o -c -std=gnu++17 -Wall -Wno-narrowing -Wno-attributes -Wno-unused-variable -Wno-unused-function -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/imgui.cpp
gcc -o src/layer.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/layer.c
gcc -o src/main.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/main.c
gcc -o src/marchingcube.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/marchingcube.c
gcc -o src/material.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/material.c
g++ -o src/meshoptimizer.o -c -std=gnu++17 -Wall -Wno-narrowing -Wno-attributes -Wno-unused-variable -Wno-unused-function -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/meshoptimizer.cpp
gcc -o src/model3d.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/model3d.c
gcc -o src/palette.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/palette.c
g++ -o src/pathtracer.o -c -std=gnu++17 -Wall -Wno-narrowing -Wno-attributes -Wno-unused-variable -Wno-unused-function -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/pathtracer.cpp
gcc -o src/quantization.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/quantization.c
gcc -o src/quickjs.o -c -std=gnu99 -Wall -Wno-unknow-pragma -Wno-unknown-warning-option -Werror -Ofast -include src/config.h -Wno-error=address -DNDEBUG -DGLEW_STATIC -DFREE_WINDOWS -Isrc -I. -Iext_src/glew -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/quickjs.c
In file included from src/quickjs.c:27:
src/../ext_src/quickjs/quickjs-libc.c:25:10: fatal error: grp.h: No such file or directory
   25 | #include <grp.h>
      |          ^~~~~~~
compilation terminated.
scons: *** [src/quickjs.o] Error 1
scons: building terminated because of errors.
make: *** [Makefile:8: release] Error 2

**Comment by guillaumechereau** [comment]
It looks like my previous commit to fix an issue on linux does not work on windows.  I'll push a fix soon.

**Comment by guillaumechereau** [comment]
Can you try again with the last commit?

**Comment by Te3Que** [comment]
![build_success](https://github.com/guillaumechereau/goxel/assets/107056703/eea90a86-7ae2-4a2f-a9b0-af566ae8af6e)
the build works now

scons: done building targets.
