### ISSUE TITLE
Cannot edit outside of Scene Box

### ISSUE THREAD

**Issue by 420noscope-exe** [guillaumechereau/goxel#324]
I made a wall by making one panel, copy & pasting it, moving all of the individual panels, and then merging all the layers.  I am using a red doorway as a guide to cut a whole out the wall using the Laser tool (also tried with brush tool).  I cannot add or subtract any voxels outside of the original scene box, regardless of whether or not it is disabled.  I could not find an answer to this in issues.  I might just be a big dummy though.

[doorway-wall.zip](https://github.com/guillaumechereau/goxel/files/12685973/doorway-wall.zip)

![Screenshot from 2023-09-21 10-37-15](https://github.com/guillaumechereau/goxel/assets/25134554/1f9abd49-42ab-4e4c-afbb-65bf4d355e96)
![Screenshot from 2023-09-21 10-37-33](https://github.com/guillaumechereau/goxel/assets/25134554/6bba4ab9-2b69-4257-87a8-81532319403a)

**Comment by guillaumechereau** [comment]
Could be a bug.  For now I suggest you change the size of the image (in the image panel) so that it fit the voxels.

**Comment by 420noscope-exe** [comment]
@guillaumechereau That works perfectly!  I am just a dummy!  I don't think that's a bug.  It makes sense that I can't edit outside of the Image box.  At least I can resize it.  Works similar to gimp or an image editing software in that regard.  Thanks!
