### ISSUE TITLE
Importing .gox Changes File Save Path

### ISSUE THREAD

**Issue by 420noscope-exe** [guillaumechereau/goxel#326]
Importing a .gox project into an already existing project changes the file path for saving.  This has caused me to accidentally save and overwrite the imported file, instead of the project that I am working on.  When this happens, I either have to use "Save as" immediately to fix the file path, or go back and remake the imported file from scratch after I have messed up.  If this is the intended behavior, can we get a setting to disable this?  I love the software but this has set me back a lot.

https://github.com/guillaumechereau/goxel/assets/25134554/24889f1e-5b47-4edb-a76c-3e2a63d7623d

**Comment by guillaumechereau** [comment]
Thanks for letting me know, I'll check how to fix that indeed!

**Comment by guillaumechereau** [comment]
OK I just pushed a fix for that, will be available in the next release.
