### ISSUE TITLE
How to install/run goxel-0.12.0-linux on Ubuntu?

### ISSUE THREAD

**Issue by cedarbob** [guillaumechereau/goxel#330]
Not sure what to do with the goxel-0.12.0-linux file (downloaded from the Goxel website) to get an executable on Ubuntu 20.  Is it a flatpack?  The last snap on snapcraft site is 0.8.1.  Any chance you can create a snap for the latest version?

Thanks.

**Comment by mrombout** [comment]
> Not sure what to do with the goxel-0.12.0-linux file

The `goxel-0.12.0-linux` file is a plain binary executable. You can start it by double-clicking it, or `<right-click>` the `Run`.

If it doesn't start you might be missing execute permissions, or be missing some dependencies. First make sure it's executable by running `chmod +x ./goxel-0.12.0-linux`, then start it with `./goxel-0.12.0-linux`. If you are missing any dependencies, it'll tell you.

I had to `sudo apt install libglfw3` before it would start.

**Comment by cedarbob** [comment]
Thanks.  First error message said I was missing only libglfw3 as well.  But after installing that, when I tried to run it I got a boatload of other missing dependencies.  Not sure if it is worth the heartburn to try to install the whole dependency tree.  I might just see what the 0.8.1 snap looks like for now.

**Comment by guillaumechereau** [comment]
I am not in control of the snap of goxel, you can try to contact the maintainer directly, maybe he can update the package.

currently I just directly copy the compiled file from my PC to GitHub, not ideal I agree, but the advantage is that the file is really small.  I could probably static link libglfw3 for now, but maybe doing an AppImage is a better solution, I don't know anything about that though.

**Comment by mgerhardy** [comment]
https://github.com/vengi-voxel/vengi/blob/f871c942f7746cd96bc016cd99eacc8c734b17e0/.github/workflows/main.yml#L139

it's quite easy if you already follow the default linux directory structure.

![Bildschirmfoto vom 2023-12-08 12-38-20](https://github.com/guillaumechereau/goxel/assets/577713/227052e0-2f70-4151-854d-1a52daaa26eb)

**Comment by guillaumechereau** [comment]
I see, and linuxdeploy automatically finds the dependencies and bundle them in the AppImage?

**Comment by mgerhardy** [comment]
yes - as far as I know ;)

**Comment by guillaumechereau** [comment]
OK, I added the github action (thanks to @mgerhardy!).

**Comment by cedarbob** [comment]
So is there a linux AppImage somewhere now?  The executable download links don't appear to have changed.

**Comment by guillaumechereau** [comment]
I haven't put it in the release yet.  You can check the artifact generated at each commit though, here is the last one:

https://github.com/guillaumechereau/goxel/actions/runs/7156494935

**Comment by cedarbob** [comment]
I got complaints trying to run the AppImage as an executable similar to those I got trying to run the ordinary Linux executable:

./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./Goxel-x86_64.AppImage)
./Goxel-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./Goxel-x86_64.AppImage)
./Goxel-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by ./Goxel-x86_64.AppImage)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./Goxel-x86_64.AppImage)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./Goxel-x86_64.AppImage)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./Goxel-x86_64.AppImage)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libmvec.so.1: version `GLIBC_2.35' not found (required by ./Goxel-x86_64.AppImage)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libglfw.so.3)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libgtk-3.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libglib-2.0.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libglib-2.0.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libglib-2.0.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libgdk-3.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libgmodule-2.0.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libcairo.so.2)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libepoxy.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libgio-2.0.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libgio-2.0.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libxkbcommon.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libdbus-1.so.3)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libdbus-1.so.3)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libmount.so.1)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libmount.so.1)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libselinux.so.1)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libselinux.so.1)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libsystemd.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libsystemd.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libsystemd.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libblkid.so.1)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/liblzma.so.5)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/liblzma.so.5)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libcap.so.2)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-WwQeb6/usr/bin/../lib/libgcrypt.so.20)

**Comment by mgerhardy** [comment]
It’s build with Ubuntu latest - but you are trying to run it with Ubuntu 20.xx. Maybe the github action should not use Ubuntu latest to build the binaries for older glibc versions

**Comment by guillaumechereau** [comment]
I switched to ubuntu 2020.04, @cedarbob can you try this build:
https://github.com/guillaumechereau/goxel/actions/runs/7257845658

**Comment by cedarbob** [comment]
Now I've got a dumb question.  How do I locate the new linux executable after following the above link?  The link takes me to the job page, but it is not obvious where the executables are.

**Comment by guillaumechereau** [comment]
a the bottom of the page, there are the 'artifacts', with the appimage (inside a zip file).  If you confirm that this one works, then I will manually upload the AppImage instead of the binary in the release files.

**Comment by cedarbob** [comment]
Sorry, I didn't notice the stuff off the bottom of my screen.  So I downloaded the AppImage, extracted the content and made it executable.  But I got the same sorts of errors as before:

rhr@bob-laptop:~/Downloads/Temp$ ./Goxel-x86_64.AppImage 
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./Goxel-x86_64.AppImage)
./Goxel-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./Goxel-x86_64.AppImage)
./Goxel-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by ./Goxel-x86_64.AppImage)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./Goxel-x86_64.AppImage)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./Goxel-x86_64.AppImage)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./Goxel-x86_64.AppImage)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libmvec.so.1: version `GLIBC_2.35' not found (required by ./Goxel-x86_64.AppImage)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libglfw.so.3)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libgtk-3.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libglib-2.0.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libglib-2.0.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libglib-2.0.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libgdk-3.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libgmodule-2.0.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libcairo.so.2)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libepoxy.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libgio-2.0.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libgio-2.0.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libxkbcommon.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libdbus-1.so.3)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libdbus-1.so.3)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libmount.so.1)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libmount.so.1)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libselinux.so.1)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libselinux.so.1)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libsystemd.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libsystemd.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libsystemd.so.0)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libblkid.so.1)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/liblzma.so.5)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/liblzma.so.5)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libcap.so.2)
./Goxel-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /tmp/.mount_Goxel-5ti7P2/usr/bin/../lib/libgcrypt.so.20)

**Comment by guillaumechereau** [comment]
OK an other try here:
https://github.com/guillaumechereau/goxel/actions/runs/7319304956

@cedarbob do you mind trying this new AppImage?

**Comment by cedarbob** [comment]
This one worked!  Thanks for getting this squared away.
