### ISSUE TITLE
When will documentation be available?

### ISSUE THREAD

**Issue by AlmostMikhail** [guillaumechereau/goxel#331]
I would like to further develop goxel so I need some documentation.

**Comment by guillaumechereau** [comment]
Do you mean documentation about the internal of the code? or about the usage of Goxel itself?

**Comment by AlmostMikhail** [comment]
> Do you mean documentation about the internal of the code? or about the usage of Goxel itself?

Internal code

**Comment by guillaumechereau** [comment]
No real plan for that at the moment.  The main readme file has some instructions to build the project, then it's mostly documentation as comments in the code.  Do you have some specific question about the code you would like me to explain?

**Comment by AlmostMikhail** [comment]
> No real plan for that at the moment.  The main readme file has some instructions to build the project, then it's mostly documentation as comments in the code.  Do you have some specific question about the code you would like me to explain?

No, but I'll have a look at your comments in code. That all.

**Comment by AlmostMikhail** [comment]
> No real plan for that at the moment.  The main readme file has some instructions to build the project, then it's mostly documentation as comments in the code.  Do you have some specific question about the code you would like me to explain?

How would you implement three.js into goxel like creating an animation timeline? What are some javascript libraries that are compatible with goxel? I want to develop for an open-source voxel engine but magicavoxel not open-source. So, I'm thinking working on goxel. Also, what is a good place to start ad a c# developer?

**Comment by guillaumechereau** [comment]
Sorry goxel is implemented in C, not javascript.  It won't work well with any javascript libraries I am afraid.  If you want to contribute to goxel you probably need to learn some C.
