### ISSUE TITLE
Request: Don't hide the coordinate widget while using the brush

### ISSUE THREAD

**Issue by jerobarraco** [guillaumechereau/goxel#337]
when painting or extruding or stuff like that. the small text that shows the coordinate in the bottom left is hidden.
i'd really would love to be able to keep seeing it.
and as a super helpful addition, if i'm using a tool like extrude or select, or shape it would be amazing to also have the distance traveled (the diff between start and end).

for example in KolourPaint you get start and size on the bottom left. or current position on just hover.
![image](https://github.com/guillaumechereau/goxel/assets/3729895/ed472472-2469-47b2-aaed-cdb93c042f17)

**Comment by guillaumechereau** [comment]
Right, I will add this.  Thanks for pointing it out.  Maybe this will wait for the merge of the new UI I am working on.
