### ISSUE TITLE
Request: Be able to make the palete show 8 colors wide.

### ISSUE THREAD

**Issue by jerobarraco** [guillaumechereau/goxel#344]
either by resizing the tool window, or by changing this on code.
i have a palette with 16 shades of each color (which is quite common).
previously it was aligned and it was all great. now it's missaligned and hard to read.
also i sometimes need to count the index of the color and this makes it harder 
(e.g. the 3rd shade in the red row)

**Comment by jerobarraco** [comment]
![image](https://github.com/guillaumechereau/goxel/assets/3729895/906e7fbb-8809-430e-9cae-7791679508de)

**Comment by guillaumechereau** [comment]
Right.  I reverted to use larger spacing between the items for now.  Need to figure out how to allow to resize the panels horizontally.

**Comment by jerobarraco** [comment]
Thanks a lot, but, maybe just making the window match 8 colors wide would be enough. resizing sounds like it could add usability issues.
Note: i usually don't like suggestions like "just make it the way i like it", but maybe that's good enough of an upgrade. i think 8 is a good number for palette colors. but other people might want different things.

also i like the spacing between the colors.

**Comment by guillaumechereau** [comment]
Yes 8 is a nice number so I'll use that for the moment.  The palette format actually allows to specify the optimal column number, so it would be nice to adapt to it, but I'll leave that to a future release.

**Comment by jerobarraco** [comment]
i've tested this is working really well on build 200. 
Thanks a lot!
![image](https://github.com/guillaumechereau/goxel/assets/3729895/9c8a249b-9094-4c91-8d96-5eb2fe1106c0)
