### ISSUE TITLE
Linux Wayland Sway WM - crash on start

### ISSUE THREAD

**Issue by ernierasta** [guillaumechereau/goxel#354]
In Linux, Wayland, Sway WM I can not run goxel, error is:

```
glfw error 65544 (Wayland: Setting window icon not supported)
goxel: src/main.c:35: on_glfw_error: Assertion `false' failed.
Aborted
```

And this is true, Sway WM do not use windows icons.

As workaround, after disabling `assert(false);` goxel will start without problem.

I am afraid that not all glfw errors are critical.

**Comment by guillaumechereau** [comment]
OK thanks I removed this assert.
