### ISSUE TITLE
Right control does not work

### ISSUE THREAD

**Issue by diego-crespo** [guillaumechereau/goxel#355]
Hi! First thank you for creating this software! I’ve enjoyed using it. 

I use a kinesis advantage 360 split keyboard, and the right control is easier to hit than the left control when using the CUA shortcuts. But all of the shortcuts only work with the left control, so hitting CTRL-Z on my right hand doesn’t work. Would it be possible to update the shortcuts to work with both?

**Comment by guillaumechereau** [comment]
I don't have access to a keyboard with right control key at the moment, but I'll check that when I do.   For custom shortcuts it could make sense to differentiate the two keys though.  What's the usual behavior of other applications?

**Comment by guillaumechereau** [comment]
Should be fixed now.
