### ISSUE TITLE
Export resolution cant be typed in 

### ISSUE THREAD

**Issue by YarlBoro** [guillaumechereau/goxel#36]
When I try to type-in exact width & height resolution values, it doesn't work. After setting value and hitting enter, value stays the same and cursor in the field keeps on blinking. So currently only way to edit values is by using arrow buttons (at least on my machines, both OSX Yosemite).

**Comment by guillaumechereau** [comment]
Right, the mac version didn't detect enter key events.  I added it now.

**Comment by YarlBoro** [comment]
Thanks!
