### ISSUE TITLE
Req: Ability to change camera movement buttons.

### ISSUE THREAD

**Issue by JohnPeppermint** [guillaumechereau/goxel#366]
Currently you can only pan the camera view with the right mouse button and orbit with middle mouse button. 
It would be great to be able to switch them around.

Thank you!

**Comment by guillaumechereau** [comment]
Would be nice to have an option for that yes.

**Comment by guillaumechereau** [comment]
I added some settings to set different keymaps as we want:

![image](https://github.com/guillaumechereau/goxel/assets/107679/b3368647-c2fc-4239-820d-178419d63226)

**Comment by guillaumechereau** [comment]
Closing this for now since I think the new keycap support should address the issue.
