### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by echoless3484** [guillaumechereau/goxel#367]
Hey there! I'm interested in using Goxel rather than my previous modelling software Blockbench but i'm wondering if the software has built in updates, and the ability to paste textures from .PNG/.JPEG/Any image format onto voxels for quick painting, is this possible?

**Comment by guillaumechereau** [comment]
Hello, to answer your questions:

- There is no build in updates, you have to manually download new versions of goxel when they get released.
- You can import an image into a plane of 1 voxel depth (import 2d image and then convert it to mesh).   But no simple way to project that into a mesh.  Do you have a use case?  Maybe it's possible to achieve something close using an intersection layer.

**Comment by echoless3484** [comment]
> Hello, to answer your questions:
> 
> - There is no build in updates, you have to manually download new versions of goxel when they get released.
> - You can import an image into a plane of 1 voxel depth (import 2d image and then convert it to mesh).   But no simple way to project that into a mesh.  Do you have a use case?  Maybe it's possible to achieve something close using an intersection layer.

Well, in my case I use blockbench for making large models but I really like my own paint editor, so Exporting that to a PNG and then dragging that texture into Blockbench and using the UV Editor to line things up and get the colors on, or just one large box big enough to hold the entire texture is really useful to have since I don't want to repeat making the textures over and over again on different apps.

One more question, do the colors of the voxels export as materials?

**Comment by guillaumechereau** [comment]
I see.  At the moment this is not very easy.  The only way I can think of would be to extrude the 2d image and then use an intersection operation to apply the color into the model.  Not very easy I guess.

The voxel colors can be exported as material or vertices attributes, at least with the gltf export.

**Comment by echoless3484** [comment]
Oh also I got another question, does goxel support objects, so if i'm making a vehicle I can easily find out which is a wheel and not by objects? They're treated as separate meshes so I'd assume that's all they are.

**Comment by guillaumechereau** [comment]
In Goxel each layer will be exported as a separate mesh, you can also give
them names, so it should cover it.

**Comment by echoless3484** [comment]
Thank you very much for the support, I'll be trying this once I get my PC out of the shop.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
