### ISSUE TITLE
Feature request: Symmetry Axes Snapping to the center of the workspace

### ISSUE THREAD

**Issue by YarlBoro** [guillaumechereau/goxel#368]
I would like to request a feature - i.e. called with a UI button - to automatically move all symmenty axes to the center point of a current layer. Tweaking symmetry options on larger models can be very tedious & time consuming. I belive this would be a good addition.

**Comment by guillaumechereau** [comment]
OK I added some buttons for that:

![image](https://github.com/guillaumechereau/goxel/assets/107679/24424dee-7828-4681-bc5c-da1c07e7e6e9)

**Comment by YarlBoro** [comment]
Thank you! This will save sooo much time.
