### ISSUE TITLE
Increase max resolution of exported image

### ISSUE THREAD

**Issue by YarlBoro** [guillaumechereau/goxel#37]
Talking about export, would it be very time consuming to increase max export resolution from 2048x2048 to 4096x4096? Higher resolution gives very nice edges without need for antialiasing, and gives more flexibility when i.e. editing assets for non-3D animation.

**Comment by guillaumechereau** [comment]
I just made a change that allow to export up to the maximum supported size.
It will change from computer to computer because it depends of the maximum texture the GPU supports.

**Comment by YarlBoro** [comment]
That is perfect, thanks!
