### ISSUE TITLE
Question: Animations 

### ISSUE THREAD

**Issue by anonimo82** [guillaumechereau/goxel#373]
Hello.
I'm just wondering if the Android version supports animations, I need to know before purchasing. 

Thanks in advance for your support. 

Have a nice day, regards =)

**Comment by anonimo82** [comment]
@guillaumechereau anything?

**Comment by guillaumechereau** [comment]
Hello,

No, Goxel doesn’t support animation at all.

Regards,
Guillaume

**Comment by anonimo82** [comment]
Thanks so much for your reply. 
I'm sad to know this.
Will it in the future?

Regards, have a nice day =)
