### ISSUE TITLE
File Dialogues not Appearing

### ISSUE THREAD

**Issue by 420noscope-exe** [guillaumechereau/goxel#377]
Using release 0.15.0 on Manjaro GNOME 6.6.34-1, I do not have the ability to save, save as, or export.  Clicking any of these does not bring up a window to name and save the file.  The only options that work under the File menu, are New and Quit.  ctrl+s does not work either.

**Comment by guillaumechereau** [comment]
Hum this is probably a bug in tinyfiledialog (https://sourceforge.net/projects/tinyfiledialogs/)

Do you have a way to test tinyfiledialog on your machine by any chance?

**Comment by 420noscope-exe** [comment]
I just changed directory to the AppImage in terminal and executed it with ./goxel to see what was going on.  This is the only way I could think of to test, as I don't develop with that library:

`Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
0.000: Register script FillRandom                                   js_goxel_registerScript (src/script.c:617)
0.000: Register script Dilate                                       js_goxel_registerScript (src/script.c:617)
0.000: Loading scripts from /home/pasquale/.config/goxel/scripts
   on_dir (src/script.c:805)
0.003: Cannot open /home/pasquale/.config/goxel/recent-files.txt: No such file or directory goxel_load_recent_files (src/goxel.c:413)
0.006: Read settings file: /home/pasquale/.config/goxel/settings.ini settings_load (src/gui/settings.c:131)


`
Then I tried using "Save as", and got:
`
missing software! (we will try basic console input)

 ___________
/           \ 
| tiny file |
|  dialogs  |
\_____  ____/
      \|
tiny file dialogs on UNIX needs:
   applescript or kdialog or yad or Xdialog
or zenity (or matedialog or shellementary or qarma)
or python (2 or 3) + tkinter + python-dbus (optional)
or dialog (opens console if needed) ** Disabled by default **
or xterm + bash (opens console for basic input)
or existing console for basic input.

press enter to continue `

I was able to save a file using the terminal, I am unsure if it actually contains anything or if it is readable as I didn't draw anything this time with the brushes:

`

Save

Save file in /home/pasquale/Applications
(esc+enter to cancel): 
test

299.421: Save to test                                                 save_to_file (src/formats/gox.c:259)
299.431: Saved test                                                   sys_on_saved (src/system.c:306)

`

**Comment by 420noscope-exe** [comment]
I ended up just having to install kdialog, seems like it didn't break any dependencies on my system, I did have to install a lot of KDE dependencies, but it seems to work now.

**Comment by guillaumechereau** [comment]
OK, that is not optimal yes.  I wonder if I should use a custom file browser instead directly inside the app for saving (at least on linux) so that we dont have to rely on external tools.

**Comment by 420noscope-exe** [comment]
I actually really liked the dialog you had before 0.14.0 on linux.  It didn't remember the last folder location for each dialog (open,save as, import, export, etc), however it worked pretty well after fixing #326.  I primarily use GNOME, it's been harder to stick with it lately as almost everyone prefers KDE/Plasma or XFCE.

**Comment by guillaumechereau** [comment]
Agreed.  For 0.15.0 I switched to tinyfiledialog but in insight this was a
mistake. Not because of tinyfiledialog itself but because it relies on
having the right program installed on the machine, and those can have
issues (my current version zenity has a bug that prevents from setting the
default save directory).

the thing that I didn’t like with previous gtk version is that it made the
AppImage unnecessarily big because I had to bundle all of gtk inside.

What I am trying for the next release is to use nativefiledialog-extended
that should support gtk or dbus.  For the AppImage I will default to
sbus that shouldn’t take much space.

Can you try the last AppImage on your machine see if it works well?

**Comment by 420noscope-exe** [comment]
I believe I already have the 0.15.0 AppImage installed, as the pacman version of Goxel was outdated (0.14.0-1).  Seems to work well on my machine.  I would also be willing to test the next AppImage with nativefiledialog-extended.

However, I will be doing more testing as I am currently using Goxel to make models for my portfolio game, and I need another batch of models.  I will update this if I find anything wrong with specifically running the AppImage on my machine

I didn't mind the extra size of the old AppImage too much, as the GTK dependencies didn't cause conflicts on my system as they were self contained in the AppImage.  Hopefully nativefiledialog-extended will give the best of both worlds: no additional dependencies, no extra file size
