### ISSUE TITLE
0.15 appimage doesn´t work on Ubuntu 22.04

### ISSUE THREAD

**Issue by jerobarraco** [guillaumechereau/goxel#378]
$ ./goxel-0.15.0.AppImage 
./goxel-0.15.0.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by ./goxel-0.15.0.AppImage)

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

please please. support 22.04 i can´t upgrade at the moment and i really want that appimage. 
thanks!

**Comment by guillaumechereau** [comment]
Can you try the one built by github, available in the CI action:

https://github.com/guillaumechereau/goxel/actions/runs/9906594286

**Comment by jerobarraco** [comment]
@guillaumechereau I just tried the action #405 and it worked!
Thanks a lot! you're awesome <3

**Comment by 420noscope-exe** [comment]
> @guillaumechereau I just tried the action #405 and it worked! Thanks a lot! you're awesome <3

It is proper etiquette to close your issue after it's been resolved!  It lightens the load on the contributors! :)

**Comment by jerobarraco** [comment]
I'm sorry i did not know. i thought that the dev might want to have control of the tickets' status.
