### ISSUE TITLE
Precise camera positioning & camera position(s) saving

### ISSUE THREAD

**Issue by YarlBoro** [guillaumechereau/goxel#38]
Something that all voxel editing tools that I know of are lacking, possibility to precisely set camera position, save it & get back to it when needed. Being able to save multiple camera positions would be even better. 

Sometimes I find "perfect view" for rendering a model. But then I notice I have to change something, so I zoom in, rotate, edit, then I try again to find view that I liked in the beginning...it is obviously never the same. It is also impossible to make few variations of same model with exactly same camera position.
Another situation that begs for precise camera, exporting frames for full rotation animation i.e. every 45 degrees. 

Someone might say this is unnecessary, because I could export my model to other program. But then 
I loose all nice stylization options of Goxel (like awesome 'smooth' mode), so I think it is worth considering.

**Comment by guillaumechereau** [comment]
Yes, this is something I was planning to do.  I just didn't find the time.  I will try to work on this this week end.

**Comment by YarlBoro** [comment]
Ok, great! 

One detail that I forgot to mention in regard to camera - I think you mentioned sth about it earlier - current draw distance is too short for big models. I tried to fit in a frame scene above 750x750x200 without success. 

All you effort is MUCH appreciated. I hope I won't piss you off with my constant flow of feature requests :)

**Comment by guillaumechereau** [comment]
The clip distance should be better now, once again you might have to wait for the next release to use it.  On the contrary I like to get feedbacks, thanks a lot.

**Comment by YarlBoro** [comment]
Great, If that is the case I got bunch of other ideas that I would like to share.

There is 'Export Animation' button present in procedural tool, that I assume suppose to save frame after each "step" of script (never worked for me, so I don't really know). It gave me an idea. Procedurally control of camera movement, would be very useful for automation of things mentioned above & making short animations. User could create scripts for various situations, i.e. go around model (full rotation), fly-over large scene, move camera along procedurally defined trajectory (like going upward along spiral), etc.  It would make repeatable export tasks quick & painless.
Automatic "closing" of trajectory (connecting its start & end) would be super useful for endless looping animations.

**Comment by guillaumechereau** [comment]
Well, I don't want goxel to become an animation tool -yet-, since that would open a whole bunch of new bugs that won't have time to fix.  The export animation is one example: I made it because I wanted to make an animated gif of the procedural rendering, but I never tried it after.  I need to fix it now or remove it.

What I would eventually like to do is incorporate a script language to goxel, so that people can write scripts plugins, doing all sort of things, including moving the camera.  But I probably won't do it any time soon unless there is a strong need for from a lot of people, or someone with codding skills decides to help.

**Comment by YarlBoro** [comment]
I see, thanks for commenting. 

> What I would eventually like to do is incorporate a script language to goxel, so that people can write scripts plugins, doing all sort of things, including moving the camera. But I probably won't do it any time soon unless there is a strong need for from a lot of people, or someone with codding skills decides to help.

Fingers crossed for help with coding. I would, but anything beyond basic JavaScript is beyond me.

**Comment by YarlBoro** [comment]
Just few hours after feature request, exactly what I imagined, incredible!
I'll check it when I get home, thanks!!!

**Comment by igoralmeida** [comment]
Hi, reviving this for a quick question: do I understand correctly that it is not possible to change the camera freely like in magicavoxel?
