### ISSUE TITLE
[Feature Request] Extrude Tool Improvement

### ISSUE THREAD

**Issue by 420noscope-exe** [guillaumechereau/goxel#380]
Current Behavior: User must click and drag on face of image to extrude that face.

Proposed behavior: The user must select the face first.  Goxel will highlight the face in a similar manner to the select tool, and have a "handle" that the user can pull or push to extrude.  The tool will have a Add and Sub setting, so the extrusion can either add or remove material.  The extrude tool would also have a distance value that can be manually edited so the user does not have to slowly drag and count voxel (would be a huge timesaver).  The distance value can be positive or negative, positive goes outward, negative goes inward.  An apply button would add the distance value to the selected face if the User opts to use the distance field instead of manually dragging the handle.

The apply button goes against the existing design language a bit, so it could be omitted and the image can be updated live with the parameters in the extrude menu instead.

Here is what it would look like:

![goxelExtrude](https://github.com/user-attachments/assets/c4c659b9-43d4-4858-9ab8-18a10506395c)

**Comment by guillaumechereau** [comment]
Thanks for the suggestion.  I’d like to keep the ability to just click and
drag though.  What I could do is add an input that would adjust the last
extrude operation for fine control.

**Comment by 420noscope-exe** [comment]
That would be awesome!

**Comment by guillaumechereau** [comment]
I just pushed some improvements to the extrude tool:

- Apply to selection if there is one.
- Add a manual input to adjust last extrude operation.

Still a bit experimental.

**Comment by 420noscope-exe** [comment]
I tested the new ci Action build #417 AppImage.  It works perfectly!  Negative numbers as well!
