### ISSUE TITLE
[Bug] Selection Tool not Obeying Size

### ISSUE THREAD

**Issue by 420noscope-exe** [guillaumechereau/goxel#384]
```
lsb_release -a                                                  
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	24.0.4
Codename:	Wynsdey

uname -r                                                        
6.6.40-1-MANJARO
```
Using ci Action #417 AppImage.

Expected Behavior:  The selection tool selects all voxels within its box.  The size (dimensions) and origin of the box can be set in the tool window.

Observed Behavior: The selection tool will erroneously ignore voxels within the box, and select voxels outside of the box.

I tried selecting the face of this layer with a h value of 1.
![Screenshot from 2024-07-28 21-37-25](https://github.com/user-attachments/assets/7285e502-c2df-4cd1-95d2-bd49dd9416c4)

It selected a strange shape, the top half had an h value of 4, the bottom had a value of 1.
![Screenshot from 2024-07-28 21-37-40](https://github.com/user-attachments/assets/be1169ca-ec59-45b7-98f9-07e6f9b87a09)

This is what it looks like after I cut it to a new layer and set the visibility to off.
![Screenshot from 2024-07-28 21-38-01](https://github.com/user-attachments/assets/5c3dcc76-d189-4692-8244-f7a3fde99845)

Another selection test.  h is set to 4.  Looks good (Except for the bottom):
![Screenshot from 2024-07-28 21-39-11](https://github.com/user-attachments/assets/5f042613-380e-490b-83f4-504bda4cbdf0)

When increased to 5, it breaks:
![Screenshot from 2024-07-28 21-39-23](https://github.com/user-attachments/assets/8dfbd494-569a-4313-aa93-60321b892641)

**Comment by guillaumechereau** [comment]
Thanks! I just pushed a fix, hopefully this doesn't break anything else.

**Comment by 420noscope-exe** [comment]
This fixed it!  Thanks!
