### ISSUE TITLE
ext_src/stb/stb_image.h fails to compile on newer versions of GCC due to -Werror=stringop-overflow

### ISSUE THREAD

**Issue by sleeptightAnsiC** [guillaumechereau/goxel#385]
Hey @guillaumechereau ,

Seems like there is internal bug in GCC that prevents `stb_image.h` from compiling.
It occurs on my side in following way when building in release:
```
g++ -o src/yocto.o -c -std=gnu++17 -Wall -Wno-narrowing -Werror -Ofast -include src/config.h -pthread -DNDEBUG -DHAVE_LIBPNG=1 -Isrc -I. -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/atk-1.0 -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/libpng16 -I/usr/include/pixman-1 -I/usr/include/cloudproviders -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/fribidi -I/usr/include/sysprof-6 -I/usr/include/gio-unix-2.0 -Iext_src -Iext_src/uthash -Iext_src/stb -Iext_src/nfd -Iext_src/noc -Iext_src/xxhash -Iext_src/meshoptimizer src/yocto.cpp
In file included from src/utils/img.c:45:
ext_src/stb/stb_image.h: In function ‘stbi__parse_png_file’:
ext_src/stb/stb_image.h:5164:56: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
 5164 |                   for (k = 0; k < s->img_n; ++k) tc[k] = (stbi_uc)(stbi__get16be(s) & 255) * stbi__depth_scale_table[z->depth]; // non 8-bit images will be larger
      |                                                  ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ext_src/stb/stb_image.h:5080:25: note: at offset 3 into destination object ‘tc’ of size 3
 5080 |    stbi_uc has_trans=0, tc[3]={0};
      |                         ^~
```

STB upstream already discussed this issue here: https://github.com/nothings/stb/issues/1642
I applied the patch from this comment to make it compilable on my side: https://github.com/nothings/stb/issues/1642#issuecomment-2112657959

Could you bump the dependency or apply said path?

Also, one more question, is there a way to build goxel with llvm/clang compilers to avoid such issues in the future?

For reference, I use GCC 14.2.1 on LinuxArch:
```
$ pacman -Qs gcc | grep 'local/gcc '
local/gcc 14.2.1+r32+geccf707e5ce-1

$ gcc --version | grep 'gcc '
gcc (GCC) 14.2.1 20240805
```

Have a nice day, and thank you for this amazing software!

**Comment by guillaumechereau** [comment]
Thanks for letting me know.  I just pushed the fix with the last version of stb_image.h.

You can compile with clang in theory with `CC=clang make`, though I just notice there are some compilation error at the moment when I try on ubuntu.  I am not sure why exactly.

**Comment by sleeptightAnsiC** [comment]
I can confirm this is fixed on https://github.com/guillaumechereau/goxel/commit/90a984fb9e242df7e26d9d9be3f1836c6095f2d1, thanks.

I also see the issue with clang on my side, this shouldn't be a big problem, I'll take a look into it.
