### ISSUE TITLE
Image plane import minor issue

### ISSUE THREAD

**Issue by YarlBoro** [guillaumechereau/goxel#39]
Imported image plane can't be removed or replaced by other image file. Each image import, adds image to existing ones. That causes distortions and flickering while moving camera. 

IMHO Image Plane would be more useful with option to turn off smoothing. Now it looks out of place when used as a ground for model. Using it as a reference for drawing model is also hard because of blurriness.

**Comment by guillaumechereau** [comment]
I think it should be fixed by now.  I will close the issue for the moment.

**Comment by YarlBoro** [comment]
Thank you!
