### ISSUE TITLE
request: Ability to change the font size on the ui

### ISSUE THREAD

**Issue by jerobarraco** [guillaumechereau/goxel#399]
I'd really would like to be able to change the font size. i find it hard to read.

**Comment by guillaumechereau** [comment]
Would be nice yes.  Can you show a screenshot of what you see though? I think on some screens or platforms there might also be some issue with the scaling.

**Comment by jerobarraco** [comment]
yups i could. though keep in mind that there is subjectiveness to the matter (that is, some ppl have better eyesight, and distance to monitor counts).
![Screenshot_20241019_173445](https://github.com/user-attachments/assets/6600754e-321e-4f12-9c23-7f649fc67b67)


here you have a view of my settings, but also a comparison with the minimum size i work with.
![Screenshot_20241019_173538](https://github.com/user-attachments/assets/6c3c81c5-2add-434c-a7c2-7d359baacfaf)

**Comment by guillaumechereau** [comment]
I just pushed a change to add a UI scale setting.  Not tested much so far.

**Comment by jerobarraco** [comment]
Awesome Thanks. ill give it a try when i can.

**Comment by jerobarraco** [comment]
The scaling works pretty. well.
but i noticed there's a gpu ram leak. not sure if it's related to this change. ill open a bug.
