### ISSUE TITLE
Color adjustments filter is not present on MacOS

### ISSUE THREAD

**Issue by YarlBoro** [guillaumechereau/goxel#400]
On MacOS there is only "Wrap Voxels" filter present in drop down menu of Filters.
It is like this in all of the artifacts generated since this feature was implemented, so it is not sth recent.

Thanks in advance for looking into this.

**Comment by guillaumechereau** [comment]
Thanks, I forgot to add the files in the Xcode project.  Should work now.

**Comment by YarlBoro** [comment]
Thanks! I have just checked recent artifact and it works perfectly.
