### ISSUE TITLE
bug: gpu ram "leak" usage rapidly increases until other apps crashes

### ISSUE THREAD

**Issue by jerobarraco** [guillaumechereau/goxel#405]
doesn't happen on 1.51

![Screenshot_20241103_184906](https://github.com/user-attachments/assets/c52b6ab4-502f-4278-a364-ca8cc900918c)

as you can see, it was open. i closed it, and it went down. i opened again and it started increasing rapidly. (it's the yellow line).

it hogs the memory usage until other apps start crashing.

found while testing #399

**Comment by guillaumechereau** [comment]
Thanks, looks like there is a serious leak!  Unrelated but is that htop? How do you get a graph like that?

**Comment by guillaumechereau** [comment]
I pushed a fix for that.  Good catch !

**Comment by jerobarraco** [comment]
thanks a lot :) i'll test soon.

the software is called "nvtop" (running on uxterm) available on ubuntu.

**Comment by jerobarraco** [comment]
works like a charm in 446. thanks so much!
