### ISSUE TITLE
text is TINY on hi-dpi monitors

### ISSUE THREAD

**Issue by meshula** [guillaumechereau/goxel#41]
Could you add an option for font size? On a hi-dpi monitor, the UI text looks like grains of dust :)

For comparison, in my own apps, I use 28 as the size for Roboto on hidpi, and 20 as the size for a smaller font for use in tooltips and the like.

**Comment by guillaumechereau** [comment]
Yes, this needs to be fixed.  I will have a look at it.

**Comment by meshula** [comment]
Thanks :)

**Comment by guillaumechereau** [comment]
Unfortunately I didn't have the opportunity to test goxel on a retina screen, so I didn't fix this issue in the last release.  This will have to wait until 0.7!

**Comment by guillaumechereau** [comment]
I just pushed a commit that might fix this issue.  This is untested.
I will probably release 0.7.0 soon, so you can then test it out.

**Comment by guillaumechereau** [comment]
OK I talked too fast.  Retina support will needs some real testing so I disabled it for the moment until I get my hands on a retina display.
