### ISSUE TITLE
Compilation error with 'qubicle_export'

### ISSUE THREAD

**Issue by TomWor** [guillaumechereau/goxel#48]
Get this trying to compile on an up-to-date Antergos (Arch-based)

```
src/formats/qubicle.c: In function ‘qubicle_export’:
src/formats/qubicle.c:139:24: error: ‘%d’ directive writing between 1 and 10 bytes into a region of size 8 [-Werror=format-overflow=]
         sprintf(buff, "%d", i);
                        ^~
src/formats/qubicle.c:139:23: note: directive argument in the range [0, 2147483647]
         sprintf(buff, "%d", i);
                       ^~~~
src/formats/qubicle.c:139:9: note: ‘sprintf’ output between 2 and 11 bytes into a destination of size 8
         sprintf(buff, "%d", i);
         ^~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
scons: *** [src/formats/qubicle.o] Error 1
scons: building terminated because of errors.
make: *** [Makefile:6: release] Error 2

```

**Comment by guillaumechereau** [comment]
Hi TomWor.

I just pushed a potential fix.  There might be a few similar errors in the code, please report them if you can.  If you just want to compile you can use the command:

    scons werror=0

That will issue warnings instead of errors for non critical problems.

**Comment by TomWor** [comment]
Hi Guillaume,
the project compiles correctly then, but when starting the executable I get

    ➜  goxel git:(master) ./goxel 
    goxel: /build/glfw/src/glfw-3.2.1/src/monitor.c:394: glfwGetVideoMode: Assertion `monitor != NULL'     failed.
    [1]    23807 abort (core dumped)  ./goxel

Which btw. is the same as when I install Goxel through the packaging system on my Arch linux.
Might it be related to the glfw version or wayland?

**Comment by guillaumechereau** [comment]
Not sure about this bug.  Probably the video mode requested is too strict and doesn't match any of the available modes on your graphic card.  What GPU do you have?

**Comment by TomWor** [comment]
I have a NVIDIA GTX 970.
I just installed goxel on my thinkpad on antergos/arch (which through AUR btw. builds from source as well) and it works! So the internal graphics card of the thinkpad can do it.
I don't know much about video modes - any hints on what I could try on my other machine?

**Comment by guillaumechereau** [comment]
Actually the problem is that glfw doesn't find your monitor for some reason.
Can you try to comment out the line:

    glfwWindowHint(GLFW_SAMPLES, 2);

in main.c (line 174) ?

**Comment by TomWor** [comment]
Still giving me the same error.
(Just to be sure: Do I have to clear-cache-something in scons or is it ok to just compile again?)

**Comment by TomWor** [comment]
OK, I got it.
I wasn't using wayland, but I had the glfw-wayland package installed instead of glfw-x11.
So I installed that and it works now - thanks for your help Guillaume.

**Comment by guillaumechereau** [comment]
I see.  I feel like I should actually stop using glfw altogether, and maybe switch to SDL2.  Somehow I think this would improve the portability.
