### ISSUE TITLE
Can't compile on MacOS 

### ISSUE THREAD

**Issue by YarlBoro** [guillaumechereau/goxel#49]
Hello 

I can't compile Goxel anymore on MacOS 10.12.6 with Xcode 8.3.3 installed. Hope it can be fixed, thanks in advance!

Here is what I got if I try to compile latest version:

> Michals-iHack:goxel michal$ xcodebuild build -verbose  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
> Build settings from command line:
>     CODE_SIGN_IDENTITY = 
>     CODE_SIGNING_REQUIRED = NO
> 
> === BUILD TARGET goxel OF PROJECT goxel WITH THE DEFAULT CONFIGURATION (Release) ===
> 
> Check dependencies
> 
> Write auxiliary files
> /bin/mkdir -p /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/SharedPrecompiledHeaders/goxel-ctapuiofkyobafebyqjcnyliprzr
> write-file /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/SharedPrecompiledHeaders/goxel-ctapuiofkyobafebyqjcnyliprzr/goxel.pch.pch.hash-criteria
> write-file /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/Objects-normal/x86_64/goxel-OutputFileMap.json
> /bin/mkdir -p /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/SharedPrecompiledHeaders/goxel-fvzpwsdttjildqgcnvhrhargqdrb
> write-file /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/SharedPrecompiledHeaders/goxel-fvzpwsdttjildqgcnvhrhargqdrb/goxel.pch.pch.hash-criteria
> write-file /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/Objects-normal/x86_64/goxel.LinkFileList
> write-file /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/goxel.hmap
> write-file /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/goxel-project-headers.hmap
> /bin/mkdir -p /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/SharedPrecompiledHeaders/goxel-fzlwlygzipgbrueaucvsorasdtwf
> write-file /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/SharedPrecompiledHeaders/goxel-fzlwlygzipgbrueaucvsorasdtwf/goxel.pch.pch.hash-criteria
> 
> CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
>     cd /Volumes/Ryzyko_1/goxel-master/osx/goxel
>     export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
>     export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
>     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name goxel -O -whole-module-optimization -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -target x86_64-apple-macosx10.9 -g -Xfrontend -serialize-debugging-options -I /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/Release -F /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/Release -parse-as-library -c -num-threads 8 /Volumes/Ryzyko_1/goxel-master/osx/goxel/goxel/AppDelegate.swift -output-file-map /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/Objects-normal/x86_64/goxel-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/Objects-normal/x86_64/goxel.swiftmodule -Xcc -I/Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/swift-overrides.hmap -Xcc -iquote -Xcc /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/goxel-generated-files.hmap -Xcc -I/Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/goxel-own-target-headers.hmap -Xcc -I/Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/goxel-all-target-headers.hmap -Xcc -iquote -Xcc /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/goxel-project-headers.hmap -Xcc -I/Volumes/Ryzyko_1/goxel-master/osx/goxel/build/Release/include -Xcc -I/Volumes/Ryzyko_1/goxel-master/osx/goxel/../../src -Xcc -I/Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/DerivedSources/x86_64 -Xcc -I/Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/DerivedSources -emit-objc-header -emit-objc-header-path /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/Objects-normal/x86_64/goxel-Swift.h -import-objc-header /Volumes/Ryzyko_1/goxel-master/osx/goxel/goxel/goxel-Bridging-Header.h -Xcc -working-directory/Volumes/Ryzyko_1/goxel-master/osx/goxel
> 
> CompileSwift normal x86_64 /Volumes/Ryzyko_1/goxel-master/osx/goxel/goxel/AppDelegate.swift
>     cd /Volumes/Ryzyko_1/goxel-master/osx/goxel
>     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c /Volumes/Ryzyko_1/goxel-master/osx/goxel/goxel/AppDelegate.swift -target x86_64-apple-macosx10.9 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -I /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/Release -F /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/Release -g -serialize-debugging-options -Xcc -I/Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/swift-overrides.hmap -Xcc -iquote -Xcc /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/goxel-generated-files.hmap -Xcc -I/Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/goxel-own-target-headers.hmap -Xcc -I/Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/goxel-all-target-headers.hmap -Xcc -iquote -Xcc /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/goxel-project-headers.hmap -Xcc -I/Volumes/Ryzyko_1/goxel-master/osx/goxel/build/Release/include -Xcc -I/Volumes/Ryzyko_1/goxel-master/osx/goxel/../../src -Xcc -I/Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/DerivedSources/x86_64 -Xcc -I/Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/DerivedSources -Xcc -working-directory/Volumes/Ryzyko_1/goxel-master/osx/goxel -emit-module-doc-path /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/Objects-normal/x86_64/goxel.swiftdoc -serialize-diagnostics-path /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/Objects-normal/x86_64/AppDelegate.dia -import-objc-header /Volumes/Ryzyko_1/goxel-master/osx/goxel/goxel/goxel-Bridging-Header.h -O -parse-as-library -module-name goxel -emit-module-path /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/Objects-normal/x86_64/goxel.swiftmodule -emit-objc-header-path /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/Objects-normal/x86_64/goxel-Swift.h -emit-dependencies-path /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/Objects-normal/x86_64/AppDelegate.d -num-threads 8 -o /Volumes/Ryzyko_1/goxel-master/osx/goxel/build/goxel.build/Release/goxel.build/Objects-normal/x86_64/AppDelegate.o
> /Volumes/Ryzyko_1/goxel-master/osx/goxel/goxel/AppDelegate.swift:47:23: error: value of type 'inputs_t' (aka 'inputs') has no member 'mouse_pos'
>         appDelegate().inputs.mouse_pos = vec2(
>         ~~~~~~~~~~~~~~^~~~~~ ~~~~~~~~~
> /Volumes/Ryzyko_1/goxel-master/osx/goxel/goxel/AppDelegate.swift:53:31: error: value of type 'inputs_t' (aka 'inputs') has no member 'mouse_down'
>         case 0: appDelegate().inputs.mouse_down.0 = (state != 0);
>                 ~~~~~~~~~~~~~~^~~~~~ ~~~~~~~~~~
> /Volumes/Ryzyko_1/goxel-master/osx/goxel/goxel/AppDelegate.swift:54:31: error: value of type 'inputs_t' (aka 'inputs') has no member 'mouse_down'
>         case 1: appDelegate().inputs.mouse_down.1 = (state != 0);
>                 ~~~~~~~~~~~~~~^~~~~~ ~~~~~~~~~~
> /Volumes/Ryzyko_1/goxel-master/osx/goxel/goxel/AppDelegate.swift:55:31: error: value of type 'inputs_t' (aka 'inputs') has no member 'mouse_down'
>         case 2: appDelegate().inputs.mouse_down.2 = (state != 0);
>                 ~~~~~~~~~~~~~~^~~~~~ ~~~~~~~~~~
> 
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	CompileSwift normal x86_64 /Volumes/Ryzyko_1/goxel-master/osx/goxel/goxel/AppDelegate.swift
> 	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
> (2 failures)

**Comment by guillaumechereau** [comment]
Thanks.  Yes I broke the osx build recently!  I will fix it today or tomorrow.

**Comment by YarlBoro** [comment]
Thanks!

**Comment by guillaumechereau** [comment]
Should be fixed now.  Please reopen if that doesn't work.
