### ISSUE TITLE
Obj Export

### ISSUE THREAD

**Issue by Cookieseller** [guillaumechereau/goxel#5]
The obj Export does not seem to work correctly, it looks somewhat distorted after importing it in e.g. Unity. Did not yet look into the exporting so I can not give you any Details on it, but i will as soon as I find the time.

**Comment by Ullarah** [comment]
Importing to MakerBot seems to have the same corruption/distortion.

![image](https://cloud.githubusercontent.com/assets/5225506/10297235/ab45a648-6c13-11e5-8e1e-ae91ad006739.png)

**Comment by guillaumechereau** [comment]
I only tested with blender on linux. Here is an obj file (renamed to .txt so that I can attach it here) that I just created with goxel.  Can you try to open it with unity or makerbot and see if it works?
[test.txt](https://github.com/guillaumechereau/goxel/files/8141/test.txt)

**Comment by Ullarah** [comment]
Looks fine to me!

![ss 2015-10-06 at 02 05 28](https://cloud.githubusercontent.com/assets/5225506/10299960/d8010f72-6c33-11e5-8245-30752bdde8fb.jpg)

What was changed?

**Comment by guillaumechereau** [comment]
Maybe it's a bug on the Windows version of goxel?

On Tuesday, 6 October 2015, Phil <notifications@github.com> wrote:

> Looks fine to me!
>
> [image: ss 2015-10-06 at 02 05 28]
> <https://cloud.githubusercontent.com/assets/5225506/10299960/d8010f72-6c33-11e5-8245-30752bdde8fb.jpg>
>
> What was changed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guillaumechereau/goxel/issues/5#issuecomment-145736903>
> .
>


-- 
Sent from my iPad.

**Comment by guillaumechereau** [comment]
OK, I fixed the problem (commit e97c4064).  This will be available when I make the next release.

**Comment by guillaumechereau** [comment]
Just released v0.1.1, the export to obj should be working on windows now.
