### ISSUE TITLE
./goxel (almost always) segfaults upon launching

### ISSUE THREAD

**Issue by Charles-the-Cat** [guillaumechereau/goxel#50]
I'm on Linux Mint 17.3 KDE. I built from source with `make release`, but now every time I launch:
`[1]    11525 segmentation fault  ./goxel`
The '11525' in that error increments every time I try to execute, usually by about 10 or 15. 
Once, it launched successfully, but I've tried dozens of times and it hasn't stayed open for more than a fraction of a second.

**Comment by Charles-the-Cat** [comment]
Note that `./goxel --help` works like you would expect.

**Comment by guillaumechereau** [comment]
Did you get the sources from github?  There is no 'install' target in the makefile.

**Comment by Charles-the-Cat** [comment]
Whoops, I definitely meant `make release`.

**Comment by Charles-the-Cat** [comment]
I deleted the binary and ran `make release` again, but after a suspiciously short compile, it left me with a similarly broken binary.

**Comment by Charles-the-Cat** [comment]
After deleting the binary again and running `scons -j 8` (as defined in the makefile) it compiled perfectly. I have no clue what exactly the problem was, but it's fixed now.
