### ISSUE TITLE
Goxel makes corrupted vxls

### ISSUE THREAD

**Issue by kmsiapps** [guillaumechereau/goxel#52]
Hello.
First of all, thank you for making such a great voxel editor ;)

But I noticed an issue : 
Exporting .gox with 63-block height to .vxl makes corrupted files, while 62-block height file are exported sucessfully. VXL supports up to 63 blocks, so It should be fine.

Here's my .gox file and its output .vxl file : 
[Source.zip](https://github.com/guillaumechereau/goxel/files/1167329/Source.zip)

I used goxel 0.6 on Windows 10 Pro x64.

**Comment by guillaumechereau** [comment]
Thanks.  There is probably a off by one error somewhere in the code.  I'll check that when I can.

**Comment by guillaumechereau** [comment]
Closing cause I think this has been fixed by now.
