### ISSUE TITLE
Export as layered BMP

### ISSUE THREAD

**Issue by ticki** [guillaumechereau/goxel#54]
That is, a sprite sheet where each sprite represents a layer. This is possible through [vox2png](https://github.com/StijnBrouwer/vox2png) and gimp, but it would be easier if it was possible to do directly in goxel.

**Comment by guillaumechereau** [comment]
Interesting idea.  I used something similar for my video game 'voxel invaders': I used a single png image and the alpha channel would represent the depth.  Still I feel that it would be better to improve goxel itself so that we can edit a slice of the model.

**Comment by guillaumechereau** [comment]
Just added experimental support for exporting a png slice:
![image](https://user-images.githubusercontent.com/107679/28914656-1ad28a58-786f-11e7-965a-53ae5bfac398.png)
