### ISSUE TITLE
Input is extremely fast.

### ISSUE THREAD

**Issue by faldor20** [guillaumechereau/goxel#56]
All input has effect exceedingly quickly, just a half second tap of the left arrow will move the pointer in the code box about 20-30 characters worth of code left. the same happens when rotating the view with key presses or trying to change the the values in boxes by clicking buttons on either side, a half second will change most from negative 1 to positive 1.
i am running windows 10
AMD fx8320, overclocked if that matters.
radeon r9 280x
asrock fatal1ty 990fx motherboard

**Comment by faldor20** [comment]
i have experienced a similar issue on my laptop, but not as extreme

**Comment by faldor20** [comment]
this seems better in 0.7.1

**Comment by guillaumechereau** [comment]
OK that's strange, I didn't do anything about that...

**Comment by guillaumechereau** [comment]
Closing for now since I cannot reproduce it.
