### ISSUE TITLE
Procedural object does not appear until i switch to brush tool goxel 0.7

### ISSUE THREAD

**Issue by faldor20** [guillaumechereau/goxel#58]
after placing a  procedural object i have to switch to the brush tool before it arrears. the code will run until completion but nothing will appear until i switch to the brush tool. if i switch before the code has finished i get a snapshot of its current progress at witch point i have to change to some other tool and then change back to the brush to see it update.
This has occurred on 3 different computers for me 2 running windows 10 one running windows 7.

**Comment by guillaumechereau** [comment]
I fixed this bug already, unfortunately after the 0.7.0 release.
I will try to make a minor release soon to fix that.
