### ISSUE TITLE
goxel 0.7 crashes when pressing the "show desktop" button.

### ISSUE THREAD

**Issue by faldor20** [guillaumechereau/goxel#59]
when i press the show desktop button in the bottom right hand corner of my screen goxel will crash.
I have tested this on two computers one running windows 7 another running windows 10, one intel the other amd. it occurs on both.
![capture](https://user-images.githubusercontent.com/26968035/29196714-9896fc34-7e79-11e7-9b2c-680c46f1ef50.PNG)

**Comment by guillaumechereau** [comment]
This should be fixed in the last release 0.7.1.
