### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [guillaumechereau/goxel#6]
I would like to point out that identifiers like "[`_BOX_H_`](https://github.com/guillaumechereau/goxel/blob/6fcfb08a1d6329fc4958682a608002c92e1fe127/src/box.h#L19)" and "[`_GOXEL_H_`](https://github.com/guillaumechereau/goxel/blob/1f417bb3373d13b567dd753c9a836c8692a17a9c/src/goxel.h#L19https://github.com/guillaumechereau/goxel/blob/1f417bb3373d13b567dd753c9a836c8692a17a9c/src/goxel.h#L19)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by guillaumechereau** [comment]
Right.  Thanks for pointing this out.  I will adjust the code.

**Comment by guillaumechereau** [comment]
Here is the fix: b6aa4d5e3
