### ISSUE TITLE
goxel does not load procedural generated objects

### ISSUE THREAD

**Issue by faldor20** [guillaumechereau/goxel#60]
after placing an procedural object the code runs but nothing will appear unitll you select the brush tool.at which point all generated voxels pop into existence. If you switch to the brush while the code is running you get a snapshot of what has been generated and you must switch to some other tool and then back to update it.
i have tested this on three separate computers 2 running windows 10 1 running windows 7, one of the windows 10 computers was AMD the other 2 Intel.

**Comment by guillaumechereau** [comment]
Thanks for the report.  This bug has been fixed already.  I will probably make a minor release soon to address this.
