### ISSUE TITLE
[Feature request] Batch rendering

### ISSUE THREAD

**Issue by FedericoCeratto** [guillaumechereau/goxel#67]
Hello and thank you for the nice voxel editor.
It would be useful to be able to run it from command line against an input file to generate an image and exit immediately. Light source and camera angle could be specified with options or another file.
Even better if it could be used as a library. Thanks!

**Comment by guillaumechereau** [comment]
Hi Federico.
I think begin able to use goxel as a library would be nice.  I am actually thinking of refactoring the code to clearly separate the voxel mesh manipulation into a standalone code.  I am a bit busy with other things at the moment but I would like to start with that for the next release, it will make the code much easier to understand I think.

**Comment by guillaumechereau** [comment]
Closing this for now, the new scripting support should be used for that.
