### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [guillaumechereau/goxel#7]
Would you like to add more error handling for return values from functions like the following?
- [calloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/calloc.html "Memory allocation") ⇒ [image_new](https://github.com/guillaumechereau/goxel/blob/6fcfb08a1d6329fc4958682a608002c92e1fe127/src/image.c#L33)
- [fseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html "Reposition a file-position indicator.") ⇒ [read_file](https://github.com/guillaumechereau/goxel/blob/dd54d7090c987ef4584936ca289805d8aaccf114/src/utils.c#L262)

**Comment by guillaumechereau** [comment]
On Tue, Oct 06, 2015 at 01:10:32AM -0700, Markus Elfring wrote:
> Would you like to add more error handling for return values from functions like the following?
> - [calloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/calloc.html "Memory allocation") ⇒ [image_new](https://github.com/guillaumechereau/goxel/blob/6fcfb08a1d6329fc4958682a608002c92e1fe127/src/image.c#L33)
> - [fseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html "Reposition a file-position indicator.") ⇒ [read_file](https://github.com/guillaumechereau/goxel/blob/dd54d7090c987ef4584936ca289805d8aaccf114/src/utils.c#L262)

Hi Markus,

Not until there is a real case bug because of it.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
Would you like to detect every error situation as early as possible?
