### ISSUE TITLE
DejaVuSans-light.ttf copyright and origin

### ISSUE THREAD

**Issue by FedericoCeratto** [guillaumechereau/goxel#74]
Hello. Can you please clarify the origin and copyright of the `data/fonts/DejaVuSans-light.ttf` font?

This will be useful for people packaging goxel in Linux distributions.

**Comment by guillaumechereau** [comment]
Hello, thanks for asking.
This is a copy of the font from the debian package "fonts-dejavu" with most glyphs removed so that it doesn't take too much space.  The script used to do so is in the sources: tools/create_font.py

Should I add a copyright notice about somewhere?

**Comment by guillaumechereau** [comment]
OK I will do that. Thanks.
