### ISSUE TITLE
Compilation error with writing between 1 and 10 bytes into a > region of size 8

### ISSUE THREAD

**Issue by alvenwei** [guillaumechereau/goxel#77]
When I compile the OpenOCD , this error happened. 
core.c: In function ‘jtag_init_inner’:
core.c:1114:21: error: ‘%d’ directive writing between 1 and 10 bytes into a region of size 8 [-Werror=format-overflow=]
sprintf(buf, "auto%d", tapcount++);
core.c:1114:16: note: directive argument in the range [0, 2147483647]
sprintf(buf, "auto%d", tapcount++);
core.c:1114:3: note: ‘sprintf’ output between 6 and 15 bytes into a destination of size 12
sprintf(buf, "auto%d", tapcount++);

Any solution to fix it ? thanks.

**Comment by guillaumechereau** [comment]
Wrong project?

**Comment by alvenwei** [comment]
You mean i am using a wrong OpenOCD version or a wrong compiler ?

**Comment by guillaumechereau** [comment]
I mean this is the issue tracker for goxel, not openocd.  Goxel doesn't use openocd.
