### ISSUE TITLE
Improve building documentation

### ISSUE THREAD

**Issue by farin** [guillaumechereau/goxel#8]
For ubuntu I need to install `mesa-common-dev` package.
And then follow
https://github.com/shurcooL/reusable-commands/blob/ed33ae496f36aaea735a1d183f77e833c92a9f3d/go-gl_glfw3_install.sh#L19-L32
to install glfw3

**Comment by guillaumechereau** [comment]
glfw3 is not available directly on ubuntu?

**Comment by farin** [comment]
ah, probably my mistake i installed libglfw-dev
but it's needed to install libglfw3-dev

**Comment by guillaumechereau** [comment]
OK thanks.  I don't use ubuntu so I couldn't check.
