### ISSUE TITLE
Huge performance regression

### ISSUE THREAD

**Issue by YarlBoro** [guillaumechereau/goxel#83]
I want to report, that some changes that happened lately, caused some performance regression.

Since around July I was using version compiled from source, and it was working really well in terms of performance and stability. Accidentally I overwrote this version with latest one compiled from source, so stupid. So I can't even say what version was working good for me. I hope it doesn't make this report completely useless.
What changed for worse for me:
- noticeably slower drawing tool speed, even with brush size of 1 or 3 vox. Earlier it was butter smooth even with brush sizes like 9-15 vox. 
- noticeably slower deleting/erasing voxels with brush tool
- huge drop in redraw speed during rotating/moving/zooming view. Earlier also it was very smooth (I mean FPS count was high) even with huge models. Now it is always 'choppy'
- there is quite high CPU load even when I just select Goxel window (30-40% of 1 cpu core utilisation),
when I do anything at all it jumps to 80-95%
- some of my bigger models with 3-4 layers that used to work in older versions, now cause Goxel to become unresponsive and needs to be force shutdown, otherwise it makes whole system quite slow

I'm on MacOS 10.12.6. I can provide more info, like crush reports or logs if necessary. 

As before, I'm grateful that Goxels exists and keeps on growing. 
Cheers

**Comment by guillaumechereau** [comment]
I made some internal changes recently that made the core of goxel easier to work with.  In the process I had to remove some optimizations, but on my machine I didn't notices that much changes.
I will try to see what can be done, it's quite annoying indeed.

**Comment by YarlBoro** [comment]
Oh, I see.
Thanks for looking into it!

**Comment by guillaumechereau** [comment]
One thing: are you sure you compile in release mode?  It makes a big speed difference.

**Comment by YarlBoro** [comment]
I will try it when I get home and will report back. Thanks for the tip.

**Comment by guillaumechereau** [comment]
I added a fps counter (debug panel on the left).  On my computer I get 60 fps with the brush tool, at least on an empty image.  Do you see a framerate drop even with an empty image?

**Comment by YarlBoro** [comment]
> One thing: are you sure you compile in release mode? It makes a big speed difference.
I use this command:
xcodebuild build -verbose  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

> Do you see a framerate drop even with an empty image?
No, FPS counter shows minimum 60. This version is big improvement. 

Don't want to sound like I'm complaining, but it is still not as fast as it used to. Also I observed few things. 
When I draw, after reaching volume of voxels above 60x60x60 (average), there is very visible drop in frame rate. It goes from stabile 60 fps to 21  fps. It happens while drawing or even "touching" surface of object (brush preview). Hovering over object with brush tool without drawing causes huge frame drop too. This frame drop is not affected by brush size, it look similar no matter if I choose brush size 1 or 50. After releasing mouse button, in about 1-2 sec FPS rise to 60. But as soon as I hover brush over surface

Another thing, frame rate is jumping to some crazy high values (600-1500 fps) during camera rotation. I don't know if it matters.

There is also one more issue that was not present before. During drawing, parts of model that are far from center of workspace, flicker every few seconds. It looks like very quick redrawing is visible in this areas. I noticed that it is happening in mostly right part of a screen, but sometimes also in upper part of screen (like 10% of height and width counting from right or upper edge).

**Comment by YarlBoro** [comment]
One more thing, this scene that I mentioned, the one that used to work, is still causing whole system to go supper slow. It is even hard to force shutdown Goxel. When I do, it crushes. Are You interested in log from this crush?

**Comment by guillaumechereau** [comment]
Yes please you can send the logs, and even more important would be a save file of the scene so I can reproduce the problem myself.

**Comment by YarlBoro** [comment]
No problem. I will send both via email.

**Comment by guillaumechereau** [comment]
OK I can confirm the problem.  This is indeed very serious.  I might even consider reverting the code to the last good version (0.7.1) !

**Comment by guillaumechereau** [comment]
I already pushed a few commits that should improve the speed a lot.

**Comment by YarlBoro** [comment]
It was that serious? Damn

> I already pushed a few commits that should improve the speed a lot.

Great, thanks!

**Comment by YarlBoro** [comment]
I've compiled today latest version & gave it quick test drive. So far so good. Performance is so much better, it's pleasure to draw in Goxel again. All problematic files are opening properly too, I can work on them again - great. If I will encounter any bugs, I will report them.

Thanks for such quick response & bug fixes, I should probably add "as always"! :)

**Comment by guillaumechereau** [comment]
Good to hear! I was really worried I would have to revert all my last few
month changes to the core!

**Comment by YarlBoro** [comment]
I can imagine!
