### ISSUE TITLE
Sub mode crashing Goxel

### ISSUE THREAD

**Issue by henriquelalves** [guillaumechereau/goxel#84]
Version: Goxel 0.7.2 (Master)
Ubuntu 17.10

When using Sub-Mode, Goxel always freezes after deleting the last voxel, or when entering Sub-Mode without any voxel on-screen.

EDIT: Also, it won't throw any error on console when running with `./goxel`

**Comment by guillaumechereau** [comment]
Thanks for the report, I will look into it.

**Comment by guillaumechereau** [comment]
I can't reproduce this.  Can you run through gdb and ctrl-C at the freeze to get an idea of where it hangs?

**Comment by guillaumechereau** [comment]
Just fixed this bug.
