### ISSUE TITLE
.vxl for Tiberian Sun and Red Alert 2 ?

### ISSUE THREAD

**Issue by Logue-Yne** [guillaumechereau/goxel#86]
Hello,

I encountered [this issue topic](https://github.com/guillaumechereau/goxel/issues/32) about the .vxl file format for Ace of Spades like games,

I use the Voxel Section Editor software to make models for red alert 2, and they also are named as .vxl files
[Documentation about the red alert .vxl format](http://xhp.xwis.net/documents/VXL_Format.txt)

Do anyone of you have insight if those two .vxl extension are the same format ? Can I use Goxel to make models for those games ?

If not, you would do the c&c modding community an awesome favor, by adding it as a supported formats, allowing them to have a user friendly voxel tool.

thx, and have a nice day

**Comment by guillaumechereau** [comment]
As far as I can tell the formats are not the same.  The format looks simple enough, I can try to add a basic export option for it.
