### ISSUE TITLE
Painting voxels with opacity.

### ISSUE THREAD

**Issue by darkhog** [guillaumechereau/goxel#88]
Well, the voxels themselves can't have opacity obviously, but I'd like to set drawing opacity for color replacer tool so I can blend colors together at lower opacity. This would help making nice color blends when you need them.
Like in the following picture - the only colors used are the green and white, but due to the fact that green was painted on white with 22.7% opacity, it blends with it nicely.
![obraz](https://user-images.githubusercontent.com/1531474/35482808-181b80cc-0432-11e8-82ee-44b336d139df.png)

**Comment by guillaumechereau** [comment]
Should be possible.

**Comment by darkhog** [comment]
Thanks. This would make coloring models easier.

**Comment by guillaumechereau** [comment]
OK I just pushed a commit that allow to do this kind of things.
![screenshot from 2018-02-04 15-36-56](https://user-images.githubusercontent.com/107679/35775318-940075a0-09c1-11e8-96a2-d61e85e66889.png)
