### ISSUE TITLE
Anyway to add an export to option?

### ISSUE THREAD

**Issue by tpebic** [guillaumechereau/goxel#93]
#Hey dude, 

Understand being able to export to goxel to files/icloud with a app folder. 

But i was wondering if there is way you could add an export to dialogue. Like have an option export a .obj to lets just say a modelling app on the ipad. Or provide the option to export the .gox file to iMessage, Dropbox, or even the files app for ios11.

My ipad doesn’t connect well to my older MacBook or my 3 year old iMac and its such a hassle to open iTunes to get a file. 

Hardest thing in general is to have to connect the ipad to a computer just to export a file to open it up on a computer. Or have to send it back through icloud to the ipad so I can open it up another app like i would for the .obj

But if there was an export  option ( that square box with a upwards triangle ) with a dialogue, I could export it to Dropbox, a iMessage, email, or even files. Or another app for that matter. 

Thanks!!!

**Comment by guillaumechereau** [comment]
I am working on a new release, on the iOS version I will try to add both iCould drive and export support.  Hope I can release sometimes in March.

**Comment by tpebic** [comment]
That would be AWESOME!!!!

And I know this might be far fetched, but any way to export marching cubes. I tried a few times to export a marching cube .obj but can't seem to figure out a way to do it.
