### ISSUE TITLE
Resize map?

### ISSUE THREAD

**Issue by Seanmatthews** [guillaumechereau/goxel#95]
After poking around in the GUI on Linux a little bit, it's not apparent how to increase the number of squares in the initial grid. How can I accomplish this?

**Comment by guillaumechereau** [comment]
You can’t at the moment. I agree that this should be configurable.

**Comment by TripleShock** [comment]
Sorry to resurrect such an old post, but this feature has been added right? I was unable to find out how to the scene size, can you please let me know how? Thanks 👍
