### ISSUE TITLE
No snap in the stable channel

### ISSUE THREAD

**Issue by popey** [guillaumechereau/goxel#96]
I notice that you're building on each commit and pushing to the snap store. Unfortunately users can't discover the snap as it's only in the edge channel. Perhaps now would be a good time to push the latest stable release to the stable channel. It looks like revisions [#222](https://dashboard.snapcraft.io/snaps/goxel/revisions/222/) (amd64), [#223](https://dashboard.snapcraft.io/snaps/goxel/revisions/223/) (i386) correspond to 0.7.3 release (commit 5cabc00). So you can go to those urls and hit "release" to push them to the stable channel :) 

Once you do that the following link will work, https://snapcraft.io/goxel which you could link to from the home page so people can find the snap easily?

In addition you may want to add an icon and some screenshots at https://dashboard.snapcraft.io/snaps/goxel/update/?step=presentation too, so the snapcraft.io store page is pretty.

We're currently lining up the calendar for the snapcraft and ubuntu social media accounts. I'd love to feature goxel in the posts coming up :) But we can't do that until it's in the stable channel.

**Comment by guillaumechereau** [comment]
Hi @popey.  Thanks, I just release the snaps now.

**Comment by popey** [comment]
Awesome! Thanks!
