### ISSUE TITLE
Add support to another plain text for gox....sutch as .goxj or .goxx

### ISSUE THREAD

**Issue by mdtrooper** [guillaumechereau/goxel#99]
Hi.

I see the new features of Goxel, the cameras is awesome. I need it to make sprites in batch...a "template" sprite with a camera in a exact position...

But the little issue is the native file format (gox) is a binary file and it is not git friendly.

maybe another native file format in json or xml or something....sutch as SVG has svgz.

But at the moment I will try to make a script to translate the original gox file format to another plain text.

Regards and thanks...Goxel is awesome

(please set a low priority this issue)

**Comment by guillaumechereau** [comment]
Hi @mdtrooper.  Ah yes still this problem.  A plain text format would be interesting that's true.  That would be quite a big change to the format though, and also it would make the files bigger (I don't know how much bigger exactly though).

For your case you could try to hack the code to add a command line input arguments to set the camera somehow.  The best would be to have a proper python or other script language binding of course.

**Comment by guillaumechereau** [comment]
Closing for now, this is too much work for me :(. I think the proper fix would be to switch to using gltf even for goxel native file, with an extension for voxels volumes.
